finalburnneo/FBNeo

makefile.mingw

Due to a race condition, `m64make.exe` did not run causing make to complain about missing `m68kops.c`. I did not check the other makefiles but the condition might be present there too.
Make invocation `make mingw510 -j5 BUILD_X64_EXE=1`
Make version `GNU Make 4.2.1`

Fix 64-bit mingw build

---

src/burn/drv/capcom/cps.h
src/burn/drv/capcom/qs_c.cpp
src/burn/drv/capcom/qs_z.cpp

Replaced the old sound emulation with the accurate one (written by me) from VGMPlay/MAME.
This is HLE so CPU usage should not be very high; the same emulator used in VGMPlay can render a complete song in a few seconds.
Some remaining issues so far:
- Not 100% tested.
- ssf2 has byteswapped samples, need to update ROM definitions to fix this.
- dino song 17 in the sound test has clicking, this is probably related to either ROM loading or timing differences (latter most likely).
- This code does not use Hungarian notation unlike the rest of FBA source code.

Accurate QSound emulation

---

src/burn/drv/capcom/cps.h
src/burn/drv/capcom/d_cps2.cpp
src/burn/drv/capcom/qs_c.cpp

Followup to my previous PR.
Remove unused variables
Remove remnants of the Mars Matrix stereo hack.
Fix noise during the 4-tap interpolation

Qsound: minor cleanups

---

src/burn/drv/capcom/d_cps1.cpp

don't leave empty, otherwise usage of strncmp(" fire", bii.szInfo + 2, 5) == 0 isn't safe

map sfzch's pause button

---

src/burn/drv/neogeo/d_neogeo.cpp

@dinkc64  As you requested, I added them.
And, could you do me a favor on hacks?
I want to add a hack of KOF 97(kof97t in HBMAME) to FB Neo, and this hack is the most popular hack of KOF97 from GOTVG. However, it is encryted and has protections. I have decrypted it and submitted it to HBMAME. Robbert has patched one protection, but there are more protections left. Can you take a look at it and help remove the protections? 
Thank you in advance. 
If you have any trouble in getting the ROMs I added, please contract me.
Regards.

Add some MS hacks with HP indicators.

---

src/burn/drv/capcom/d_cps1.cpp

It's a fixed version of wofch. The patch is made by rockywall, and it makes wofch is more similar to Playstation/SEGA Saturn verison.
1. Three player mode is enabled.
2. Bonus point is changed to 300,000.
3. Continue with two lives.
4. Hidden mode is enabled.
5. Restore red blood palette for hidden mode.
6. Many bug fixes to character moves and horizontal coordinate.
7.The hidden mode menu can be directly displayed without a password.

Added wofchp.

---

src/intf/video/pi/vid_pi.cpp

Fixes screen corruption issue in Rygar (and any other game with a particular screen aspect ratio) in the Rpi build.

Fixes #170 - Rygar screen corruption

---

.gitignore
makefile.pi
src/burner/pi/main_pi.cpp
src/burner/pi/run_pi.cpp
src/dep/pi/gles/pigl.h
src/dep/pi/gles/pigl_dmx.c
src/dep/pi/gles/pigl_drm.c
src/intf/video/pi/vid_pi.cpp

This PR adds initial support for rendering via DRM, so the emulator should now be playable on the Pi 4. It's likely unoptimized and could use additional tweaking; I'll be chipping away at it as time allows.
It also properly handles driver init errors by propagating them up the initialization chain (#173).

Pi 4 Support

---

README-PI.md
src/dep/pi/gles/pigl_drm.c

Small modification that includes instructions on how to build on Pi 4 and renderer info for the DRM build (for troubleshooting).
It's clear that FBNeo isn't alone in rendering issues on Pi4 - internet is awash with complaints about poor fps performance with code that otherwise worked fine on earlier versions of Pi.  It's possible that this is largely due to vast majority of code being based on the same rendering example (some rendition of https://github.com/eyelash/tutorials/blob/master/drm-gbm.c), but it's also possible that the drivers used by the new Pi still need work.
I will run some additional profiling to see if I can pin down the source of the problems, but this is probably it for a while - as far as Pi 4.

Added basic documentation & renderer info

---

src/burn/drv/pre90s/d_armedf.cpp

- Revert unneeded change in PR #250.
- Fixed crash on player change in Armed Formation two-player game. This was caused by overflow memory access in sprite drawing.

g_armedf.cpp crash and minor fixes

---

src/burn/drv/konami/d_twin16.cpp

(ex. Missing upper left of Gradius II "0" character)

twin16 : Fixed missing first byte when converting from 4bp

---

src/burn/drv/neogeo/d_neogeo.cpp

when battles begin in kof99eur and kof99sr. I just tested KOF99, maybe other KOF clones need similar patches.
I have ported all timer patches from HBMAME. So when other KOF clones/hacks need them, we can just apply them.
static INT32 Kof97TimePatchInit() // Done!
{
INT32 nRet = NeoInit();
UINT8* ROM = (UINT8*)Neo68KROMActive;
ROM[0X263BB] = 0x65;
return nRet;
}
static INT32 Kof98TimePatchInit() // Done!
{
INT32 nRet = NeoInit();
UINT8* ROM = (UINT8*)Neo68KROMActive;
ROM[0x30633] = 0x65;
return nRet;
}
static INT32 Kof99TimePatchInit() // Done!
{
INT32 nRet = NeoInit();
UINT8* ROM = (UINT8*)Neo68KROMActive;
ROM[0x2ABE9] = 0x65;
return nRet;
}
static INT32 Kof2k2TimePatchInit() // Done!
{
INT32 nRet = NeoInit();
UINT8* ROM = (UINT8*)Neo68KROMActive;
ROM[0x12511] = 0x65;
return nRet;
}

Fix timer jumping to zero

---

src/burn/drv/pre90s/d_renegade.cpp

Technos games are notorious for having slowdown here and there, kunio kun and renegade are no exception however the bootleg sets do not do this, but then again they dont have the protection 
MCU either
Faithful emulation with a little slowdown vs faster emulation with a question mark due to the missing MCU  you takes your choice

New Renegade bootleg set [TwistedTom and Osso13]

---

src/burn/drv/pgm/d_pgm.cpp

b04401w064.u1 on all the other ddpdoj sets was found to be corrupt (doesn't match checksum on ROM) this was redumped and replaced in the sets, exept for in the bootleg set, which is based around the corrupt dump (nw)
Credits Shoutime - David Haywood

Add new redump of b04401w064.u1 for the Do-Donpachi 3 sets

---

src/burn/drv/capcom/d_cps1.cpp

The game is still marked as non working in MAME even with the new dump of the bad gfx rom, although this could simply be an oversight i'll leave it as not working here for the moment.

Redumped gulunpa ROM 1

---

src/burn/drv/sega/d_outrun.cpp
src/burn/drv/sega/sys16_run.cpp

It turns out it won't work for every game, for `toutrun` it's saving something but fail applying it : 
```
Applied Hi Score Memory Range 0 on frame number 35583
Failed attempt to apply Hi Score Memory Range 1 on frame number 35583
```
`outrun` hiscores work properly though, any idea ?

outrun: support for hiscores

---

makefile
makefile.mamemingw
makefile.mingw
makefile.sdl
makefile.sdl2
src/burner/win32/inps.cpp

Are these changes ok? 
Basically I have changed the mamemingw makefile so it doesn't require mingw mkdir, which means FBNeo can now be built with http://www.winlibs.com/ out of the box, which is nice if you want an easy way of using GCC10 for example. I have checked with @JacKc029735 and he very kindly confirmed that this doesn't break his build environment. 
Building with GCC10 threw up a warning in inps.cpp. The change I made seemed like the most sensible fix, and as far as I can tell doesn't break any other build when running it and trying that dialog. I have no done any win32 programming for ages though so it's possible I have made a terrible mistake...
Finally, I added a BUILD_NATIVE flag to all the GCC makefiles, and if this is defined it will build using -march=native …

Mamemingw changes

---

src/burn/drv/pre90s/d_snk.cpp

0.221: Guru added clone T.A.N.K (bootleg, 8-way joystick).
8th June 2009: Guru - TNKIII (1985 SNK bootleg joystick version) arrived. Thanks to Gp-Lee.

New working clone T.A.N.K. (Bootleg, 8-way Joystick)

---

src/burn/drv/pre90s/d_gaplus.cpp

- Fixed displaying of starfield
- Fixed scrolling speed and direction ([MAME Testers-00434](https://mametesters.org/view.php?id=434))
- Added top and bottom clipping ([MAME Testers-07663](https://mametesters.org/view.php?id=7663))
- Modified to use sprite color instead of text color with refer to the PCB
- Added blinking when the movement of the star changes
- Add service mode in DIPSW setting

gaplus : Starfield fix and add service mode in DISPW

---

src/burn/drv/pgm/pgm_run.cpp

@dinkc64 re big-endianizing those handlers : finally i wonder if it's not required, 2 reasons : 
- it fixes the following error on ddp2
- there is something similar done in m68k : 
https://github.com/finalburnneo/FBNeo/blob/b51b55f2bdef3f21dbffd501984f857841a151ea/src/cpu/m68000_intf.cpp#L333
https://github.com/finalburnneo/FBNeo/blob/b51b55f2bdef3f21dbffd501984f857841a151ea/src/cpu/m68000_intf.cpp#L375-L378

pgm: big-endianize attempt 2

---

src/burn/drv/spectrum/d_spectrum.cpp

There's no Saboteur 128k, the rom with the respective CRC was for Saboteur 2.

Same for other 128k games, removed Saboteur 128k

---

src/burn/drv/spectrum/d_spectrum.cpp

Also removed the parent ROM, Savage 128. It was the 2nd part masquerading as a full game.

Same treatment for Savage as other multi-parts.

---

src/burner/win32/main.cpp

fbneo <game> [-listinfo|-w|-a|-r <width>x<height>x<depth>|-ips <dat1>, <dat2>, <dat3>, ...]
-ips = Start from the game of configured ips
-ips <dat1>, <dat2>, <dat3>, ... = Specify IPSes to start the game (need to exists)
<dat1> = xx or xx.dat or "1 2" or "1 2.dat" ...
Examples:
fbneo nes_smb -r 800x600x32 -ips "super ale bros (hack)"
fbneo dinods -w -ips 1.dat, 2, "34 5.dat"
fbneo sfa3 -ips

mian.cpp: update cmdline for ips

---

src/burn/drv/neogeo/d_neogeo.cpp

Adjusted the NULL, HACK and CLONE tags for the appropriate new hacks. not sure if I need to *replace* any of those parent sections, like p1.p1 or if keeping it there should be fine for the hack, I'm thinking that's part of what causes Samurai Shodown's checksum error so I'm trying with this for now. AOF3 and KOF95 don't replace any files for their respective hacks.
Tried my luck with the tabbing sections for a good hour so far and haven't had any luck with this
{ "069-p1.p1",    0x100000, 0xa8bcfbbc, 1 | BRF_ESS | BRF_PRG }, //  0 68K code			/ TC538200
{ "069-p1bh.p1",    0x100000, 0xB8362F59, 1 | BRF_ESS | BRF_PRG }, //  1 68K code			/ TC538200
{ "069-sp2.sp2",  0x200000, 0xdbe963ed, 1 | BRF_ESS | BRF_PRG }, //  2 					/ TC5316200
I tab into the messed up section in the middle and it …

Neo Geo Hack Set

---

src/cpu/tms34010_intf.cpp

../../cpu/tms34010_intf.cpp:102: error: integer constant is too large for 'long' type
make: *** [../../cpu/tms34010_intf.o] Error 1
make: Leaving directory `/home/crystal/tmpwork/FBNeo/src/burner/libretro'

Fix integer constant is too large for 'long' on old GCC

---

src/burn/drv/pst90s/d_3x3puzzl.cpp
src/burn/drv/pst90s/d_bestleag.cpp
src/burn/drv/pst90s/d_bigstrkb.cpp
src/burn/drv/pst90s/d_blackt96.cpp
src/burn/drv/pst90s/d_crospang.cpp
src/burn/drv/pst90s/d_cultures.cpp
src/burn/drv/pst90s/d_dooyong.cpp
src/burn/drv/pst90s/d_dreamwld.cpp
src/burn/drv/pst90s/d_drgnmst.cpp

Before continuing I ask you for an opinion about:
`static INT32 DrvScan(INT32 nAction, INT32 *pnMin)` and `*pnMin = 0x029707;`
In the past it never big endian swapped.... but i think it must be swapped.... and that is weird.
What is that value for?

Some pst90s Big Endian fixes

---

src/burner/win32/sel.cpp

The gamelist window has a low initial height and limited visible content
1. Enlarge the window by dragging the edge of the window (fbneo's default scheme)
2. Add a button to maximize and restore the window (another way)

win32ui: Add a maximize and restore button to the form [select game]

---

src/burn/drv/pst90s/d_kaneko16.cpp

berlwall, packbang, blazeon, wingforc, explbrkr, gtmr, gtmr2, mgcrystl, shogwarr, brapboys and their clones are ok.
bloodwar and bonkadv no.
I spent a lot time with this (bonkadv):
Finally i understood the problem: tables inside `kanekotb.h` and how `BloodwarMCURun()` and `BonkadvMCURun()` use them.
Copying memory from those tables in a Big Endian machine, values are already swapped. So destination will contain memory not swapped and memory swapped in other locations.... 
I kept `BloodwarMCURun()` and `BonkadvMCURun()` not changed. 
Help :-P

d_kaneko16.cpp - Partial Big Endian Fix

---

src/burn/drv/neogeo/d_neogeo.cpp

As per suggestion I removed the unneeded parent files for both 033-m1h.m1 and 033-p1.p1, I also added EGCG/EGGT for the imitation PS1 hack for King of Fighters 97 since going by the little that mentions the existence of the hack, the only name I found mentioned was that one.

Fatal Fury 1 Boss Hack Cleanup

---

src/burn/drv/megadrive/megadrive.cpp

Attempt at fixing : 
```
../../burn/drv/megadrive/megadrive.cpp:4282:10: runtime error: store to misaligned address 0x7f568b7ad3f1 for type 'INT32', which requires 4 byte alignment
0x7f568b7ad3f1: note: pointer points here
00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00
^ 
../../burn/drv/megadrive/megadrive.cpp:4283:10: runtime error: store to misaligned address 0x7f568b7ad3f5 for type 'INT32', which requires 4 byte alignment
0x7f568b7ad3f5: note: pointer points here
80 ff 40 11 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00
^ 
../../burn/drv/megadrive/megadrive.cpp:4290:7: runtime error: store to misaligned address 0x7f568b7ad3f9 for type 'INT32', which requires 4 byte alignment
0x7f568b7ad3f9: …
```

megadrive: attempt at fixing misaligned address access

---

README-SDL.md
src/burner/sdl/run.cpp
src/burner/sdl/sdl2_gui.cpp
src/burner/sdl/sdl2_gui_ingame.cpp
src/intf/video/sdl/vid_sdl2.cpp

- SDL2: Add Pause when lost focus on window  and limit usage of CPU
- SDL2 MENU : limit usage of CPU
- Update Readme.SDL
- SDL2 GUI : Add game genre information
- SDL2 GUI : Reorganization of game information (genre, number of players, etc.)
- SDL2 GUI : limit CPU usage
- SDL2 GUI : add gamepad name (when found in console)
I dont test building on linux, if possible to test before accept this commit ?

SDL2: improvements

---

src/burn/drv/pre90s/d_asteroids.cpp
src/burn/drv/pre90s/d_bzone.cpp
src/burn/drv/pre90s/d_omegrace.cpp
src/burn/drv/pre90s/d_quantum.cpp
src/burn/drv/pre90s/d_starwars.cpp

all those vector games don't have smooth lines at the moment, this is especially visible if you use the hires mode and look at some scrolling (watch letters in starwars intro, or landscape in bzone), setting pixel aspect ratio to 1:1 (display aspect ratio to width:height) everywhere seems to fix this issue.
btw, i did this PR without merging it because i'm not sure about this solution, my other theory would be that current 4:3 display aspect ratios are actually fine, but the line drawing algorythm need to somehow account for it.

1:1 pixel aspect ratio for vector games

---

src/burn/drv/megadrive/d_megadrive.cpp

Thunder Fox (Hack, Spanish) now with correct CRC [IPS + Checksum Fix] ~ 20h35 utc-3, 2020-12-31.

Megadrive: 'tfoxs' CRC fix

---

src/burn/drv/pre90s/d_cop01.cpp

Fixed various sound issues in Might Guy so that it sounds almost exactly like PCB.
- BGM tempo was unstable.
- The frequency setting of the DAC and the clock of the timer are now linked.
- When the sound driver changed the DAC's clock, the loop count ($C010) that calls the timer in anticipation of this action was fluctuating in the range of 2 to 4 times.
- The playback frequency of the DAC is incorrect.
- I changed the frequency so that the sound plays as per the PCB.
- Implemented a protect command 0x11 to stop the DAC.
- This is needed to stop the DAC when the psycho gun is stoppedv
- Bug in which some DAC sound effects did not sound correctly.
- This is not in MAME, but seems to be a problem when it was ported to FinalBurn.
- The DAC data reference address mask was wrong.

d_cop01.cpp: Fix Mighty Guy some sound issues

---

src/burn/drv/capcom/cps_rw.cpp

@dinkc64 the current 100% dial speed for this game feels wrong, if you look at the attract mode for some time, you'll see a player with a flamethrower rotating a lot faster than what we allow at 100% analog speed, this is only a test fix because i guess we should actually move to `ProcessAnalog` here ?

increase default dial speed in Forgotten World

---

src/burn/drv/sega/d_ybrd.cpp

@dinkc64 i can't tell if there is a speed difference between 0x80 and 0xff values, however there is a specific small animation around the reactors when you go beyond 0x80, and MAME seems to think a full axis is required here.

split throttle into 2 pedals for gforce2

---

src/burn/burn_endian.h

PS3 build fix about:
include/math.h:118: error: template with C linkage

Fix PS3 build

---

src/burn/drv/megadrive/d_megadrive.cpp

Correct CRC for 'ejimp', previous one is the same than 'ejim'
24/06/2021 12h04 (utc -3)

Megadrive: fixed 'ejimp'

---

src/burn/drv/spectrum/d_spectrum.cpp

Correct crc and size for lareliquia, previous one is the same than english version (relic)
2021/07/04 ~ 11h41 (utc -3)

Spectrum - lareliquia: crc/size fix

---

src/burn/drv/toaplan/d_enmadaio.cpp

Notes state it so, as the game seem to require a special controller that doesn't seem to be supported in FBNeo at this time.

Mark enmadaio as Not Working

---

src/burner/win32/main.cpp

The Mortal Kombat games would play audio at the wrong speed and pitch when being loaded from via a command line argument (EG: "umk3 -w"). These two lines of code restart the audio subsystem and fix the audio pitch fix for all Mortal Kombat games.

Updated main.cpp to fix the broken Mortal Kombat audio

---

makefile.sdl2

Allows EmuELEC aarch64 to cross compile FBNEO SDL2, by allowing it use system libpng and compiling the tools needed with host_cc.
The reason we need system libpng (enabled by FORCE_SYSTEM_LIBPNG) is because the one included complains about NEON support. 
Please review and test in other environments, as I have only tested this while cross compiling but the changes should not interfere with regular builds. 
NOTE: Since FBneo is not available with SDL2 GLES, it needs gl4es as external dependency to work in EmuELEC .

Allow cross compiling on EmuELEC aarch64 (possibly others?)

---

src/burner/win32/systeminfo.cpp

1、Windows 11 Support
2、CPU Detection enabled for GCC builds
-------------------
VS
GCC

Add: Windows version & CPU Detection

---

makefile.vc

[Tip] do not use: -j[n] parallel compilation
[1] add incdir - dx9 / xaudio2
[2] disable DMIPS3_X64_DRC (form makefile.burn_rules)

Fixed compilation failure (vc cmd)

---

src/burn/drv/dataeast/d_dec0.cpp
src/burn/drv/dataeast/d_dec8.cpp
src/burn/drv/konami/d_jackal.cpp
src/burn/drv/pre90s/d_alpha68k2.cpp
src/burn/drv/pre90s/d_snk.cpp
src/burn/drv/pre90s/d_snk68.cpp
src/burn/drv/pst90s/d_seta.cpp

Following the previous PR, I'm adding the same support to all the other drivers that have support for a "rotate button" to adjust rotary controls. These are (not exclusively, I didn't include some bootlegs and variants):
- d_seta: downtown, calibr50
- d_snk68: ikari3w, searcharu
- d_snk: bermudat, gwar, tnk3, ikari, victroad /// has issues
- d_alpha68k2: timesold, Btlfield
- d_jackal: jackalr, topgunbl
- d_dec8: gondo
Some notes of what I did and what I found:
- Most games work exactly as intended, which is good. However, this implementation surfaced some existing issues with the existing "rotate button" in games from the *d_snk* driver that I could not solve after digging into the code. Specifically the following:
> * Bermuda Triangle (bermudat): When pressing the rotate button and Fire …

Add right-stick rotary support to other drivers

---

src/burn/drv/megadrive/d_megadrive.cpp
src/burn/drv/nes/d_nes.cpp

nes : Magical Kid's Doropie (Prototype)
megadrive : Time Trax (Prototype)

nes / megadrive - add 2 prototype games

---

makefile
makefile.mamemingw
makefile.mingw
makefile.sdl
makefile.sdl2
makefile.vc
src/burn/drv/capcom/d_cps1.cpp

Precompiled instructions are off by default.
Enable by HACK_SOUND=1

CPS1 games (No sound) with QSound [Hack]

---

src/burn/drv/neogeo/d_neogeo.cpp

Correct P2 and M1d as on HBMAME.
current version is just hbmame p2 + 1mb of junkdata (bytes00 and bytesFE).
Use the '.bat' to generate junkdata file and join the roms with junkdata file and:
remix pro    - p2 4mb (91668d86) + junkdata = p2 5mb (37a818ed).
original aes - p2 4mb (91eea062) + junkdata = p2 5mb (aa4ef2f0).
[create_junkdata.zip](https://github.com/finalburnneo/FBNeo/files/8465166/create_junkdata.zip)

Neo Geo: kof2001rpf

---

src/burn/drv/neogeo/d_neogeo.cpp

Obtained applying the patch 'ps210-p3.ips' in original rom '271-p3c.p3' (with crc-aec5b4a9).

kf2k3ps2sp: correct crc for P3

---

src/burn/burn.h
src/burn/drv/capcom/d_cps1.cpp
src/burn/load.cpp
src/burner/win32/ips_manager.cpp

[1] cps-1 cpsrom is reserved to 0x300000 (captcomm hack).
[2] Lift the limit in byteswap state that [ipsmaxlen] cannot be greater than [romlen].

update : ips feature extensions

---

src/burner/qt/burner_qt.h
src/burner/qt/main.cpp
src/burner/sdl/ips_manager.cpp

Fixed a bug for platforms other than win32, where [GetIpsesMaxLen] did not have a defined bug.

Fixed compilation errors

---

src/burn/drv/neogeo/d_neogeo.cpp
src/burn/drv/neogeo/neo_run.cpp
src/burn/drv/neogeo/neogeo.cpp

[1-1] NON-PCB CMC-encrypted games now allow Sprite-ROM to be longer than 0x4000000;
[1-2] The excess also applies to CMC encryption/decryption.
[2-1] In the case of ips, the reserved length of P-ROM/C-ROM/V-ROM is increased.
[2-2] ips extends the length of sprite-ROM, and in this mode, there is a judgment of the true length to ensure that CMC built-in TextRom can be correctly recognized.
[2-3] When synchronizing ips cmc decrypts the length of the temporary memory, it avoids overflows caused by inconsistencies in the length of the two temporary memory.

neogeo update

---

src/burn/drv/neogeo/d_neogeo.cpp

[1] In mslug5init decryption, byte interleaving is allowed to expand to 0x500000 - 0x700000, to accommodate increased ips capacity.
[2] Turn off PVC protection in ips environment.
-Test-
binary file:
[fbneo.zip](https://github.com/finalburnneo/FBNeo/files/8681808/fbneo.zip)
ips:
[mslug5.zip](https://github.com/finalburnneo/FBNeo/files/8681809/mslug5.zip)

update d_neogeo.cpp for ips

---

src/burner/win32/sel.cpp

[1] Whether IDC_SEL_APPLYIPS is enabled must be subordinate to IDC_SEL_IPSMANAGER to verify that xxx.dat is not removed after saving config.
[2] Reduce useless array lookups.

sel.cpp : Update IDC_SEL_APPLYIPS enabled logic

---

src/burn/drv/capcom/d_cps1.cpp
src/burn/drv/neogeo/d_neogeo.cpp
src/burn/drv/pre90s/d_jack.cpp
src/burn/drv/pre90s/d_sidearms.cpp

[d_cps-1.cpp] wofjdr update to 20220525.
[d_neogeo.cpp] kof98eckg has some graphics errors, returning Build 2019-02-17.
<graphics error>
<Build 2019-02-17>
[d_sidearms.cpp] Sync mame, adjust rom labels for [turtship] and its clones.
[d_jack.cpp] Sync mame, adjust rom labels for [brix].
test sets:
https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=sharing

update cps-1 / neogeo hack games & pre90s

---

src/burn/drv/dataeast/d_brkthru.cpp

sync mame
keep the format consistent
brkthrut:
brkthrubl:

d_brkthru.cpp : add brkthrut & brkthrubl

---

src/burner/luaengine.cpp
src/cpu/m68000_intf.cpp
src/cpu/m68k/m68kcpu.c

I can't figure out why the CALLBACK_PC_CHANGED  callback is not exposed to lua when working this way. It seems to never get updated!
Getting the Z80 to work has similar problems as m68k, It seems the way it was handled was changed as well since fba-rr.
Let me know what errors I have made, and I will try my best to fix them.
The changes have been tested by Alice and myself from the LUA scripting end.

(luaengine.cpp,m68kcpu,m68000_intf) - fix luamemhook fns

---

src/burn/drv/midway/d_wunit.cpp
src/burn/drv/neogeo/d_neogeo.cpp
src/burn/drv/sms/d_sms.cpp

1. WUNIT, umk3p: correct labels for u114~u117
2. SMS
waimanusms: romname in lowercase.
voyage: correct version in filename.
3. NeoGeo, better labels for kof96ae and kof96ae20

NG/SMS/WUNIT: Some changes in rom labels.

---

src/burner/conc.cpp
src/burner/sdl/sdl2_gui_ingame.cpp
src/intf/video/sdl/vid_sdl2.cpp

Cheats menu is now populated and working in the ingame menu.
(conc.cpp) Also ignore carriage return chars when parsing cheats *.ini
Some games have big list of cheats that won't fit on screen, so scrolling is also implemented.
Dynamic menu title helps navigation, particularly when going into sub menus.
Corrected aspect ratio of game screenshot shown in ingame menu.
Also, game screenshot is only shown in top menu, as it can make difficult to read menu's options when text overlaps.

fbneo sdl2: enabling cheats in ingame menu

---

src/burner/sdl/main.cpp
src/burner/sdl/sdl2_gui_ingame.cpp

Now if a controller was previously mapped it will be restored instead of making null all binds.
Unrelated fix (main.cpp): moved declaration of "do_reload_game" variable to avoid breaking Linux SDL 1.2 build.

SDL2: Improve resetting buttons mapping by restoring previous mapping

---

src/burner/sdl/sdl2_gui_ingame.cpp

Build cheats list for menu once per game, avoiding rebuilding the list every time user call the cheats menu.
Don't try to run cheats without options (some cheats are only text instructions or blank lines for grouping cheats).

SDL2: Slight improvement in cheats menus

---

src/burner/sdl/burner_sdl.h
src/burner/sdl/inpdipsw.cpp
src/burner/sdl/main.cpp
src/burner/sdl/sdl2_gui_ingame.cpp
src/intf/input/sdl/inp_sdl2.cpp

DIP switches menu working, similar to cheats menu, with check boxes and different color for changed DIPs.
Note: if we exit game with changed DIPs, those are saved in <romname>.ini and become the default values in future runs. Deleting <romname>.ini restores real default DIPs.
Also added a new option in ingame menu: Reset Game.

SDL2: DIP switches ingame menu; also add Reset Game to ingame menu

---

src/burner/macos/burner_macos.h

macOS port fails to build because some declarations are missing in burner_macos.h

SDL2: fix missing declarations for macOS build

---

src/burner/sdl/input_sdl2.cpp

When using keyboard only a controller for player 2 was properly set.
When not using keyboard, controller 3 and 4 would not be properly mapped.
Note about function GameInpConfigOne: seems to have cases that are not called in any way (X-Arcade and HotRod).

SDL2: fix 4 players support

---

src/burner/gami.cpp
src/burner/sdl/drv.cpp
src/burner/sdl/input_sdl2.cpp
src/burner/sdl/main.cpp
src/burner/sdl/sdl2_gui_ingame.cpp
src/intf/input/sdl/inp_sdl2.cpp

Fixed inputs always being reset to defaults (ignoring custom inputs from <romname>.ini).
Also fixed loading presets when <romname>.ini does not exist.
Note: -joy parameter will always ignore inputs from *.ini and set joystick inputs for all players.
If the -joy parameter is used when a game is launched for the first time, player 1 inputs will be set to joysticks and won't work without -joy after that, because without -joy the keyboard is assigned to player 1.

SDL2: fix loading inputs from *.ini

---

src/burner/cong.cpp
src/burner/gami.cpp
src/burner/sdl/burner_sdl.h
src/burner/sdl/config.cpp
src/burner/sdl/input_sdl2.cpp
src/burner/sdl/main.cpp
src/burner/sdl/run.cpp
src/burner/sdl/sdl2_gui.cpp
src/burner/sdl/sdl2_gui_ingame.cpp
src/burner/sdl/stated.cpp

IMPORTANT NOTE: This commit changes folders paths for <romname>.ini, *.fs, *.nv, samples and *.dat.
Some paths were not consistently defined and used. Now support paths are similar to those used in Windows.
Details about what changes:
- hiscore.dat must be placed in ~/.local/share/fbneo/support/hiscores/ (this is also where *.hi will be stored);
- samples *.zip must be placed in ~/.local/share/fbneo/support/samples/
- <romname>.ini, *.fs and *.nv are all stored in ~/.local/share/fbneo/config/games/
- when using "-dat" parameter, the *.dat files will be created in ~/.local/share/fbneo/support/lists/dat/
- all support folders are created at first launch.
Other code changes:
- main.cpp was checking fbneo.ini two times, and one of those times was too early (making highscores disabled by …

SDL2: fix support paths (that fixes hiscores and samples)

---

src/burner/sshot.cpp

Screenshots would not be saved because the default folder was not automatically created.
Using ingame menu "Save screenshot" option will now save png files in ~/.local/share/fbneo/screenshots/

SDL2: fix screenshot not being saved

---

src/burner/sdl/sdl2_gui_ingame.cpp

With this, "Save Screenshot" will exit ingame menu, returning to game with a success or error message displayed on screen, similar to what "Save State" and "Load State" do.

SDL2: make Screenshot behave like Save/Load state

---

src/burn/drv/pst90s/d_ssv.cpp

Primarily to fix Change Air Blade (`cairblad`), because it does not like it if NVRAM initialization gets skipped somehow.

d_ssv: save NVRAM in states for games that have it mapped

---

src/burner/sdl/run.cpp
src/burner/sdl/sdl2_gui_common.cpp
src/intf/video/sdl/vid_sdl2.cpp

Fixed:
- image would not be centered when going from window mode to full screen;
- window would be bigger than screen when exiting full screen mode.
Also done some code cleanup (mainly avoiding repetitive if tests).

SDL2: Fix fullscreen not centered or distorted

---

src/burn/devices/thready.h
src/burner/sdl/sdl2_gui_ingame.cpp

@cjom getline is posix so ive added the function for windows as its missing. The only other alternative is to use c++ getline. The other fix is to disable unicode for all windows builds accept the original fork that uses it.

fix sdl windows build

---

makefile.sdl2

Fix cross compile for mingw. Will post details of why this is needed.
```
#set env flags for mingw
. /usr/bin/mingw-env x86_64-w64-mingw32  
[FBNeo]$ pkgconf --libs sdl2
-L/usr/x86_64-w64-mingw32/lib -lmingw32 -lSDL2main -lSDL2 -mwindows 
[FBNeo]$ sdl2-config --libs 
-L/usr/lib -pthread -lSDL2
```
I really only have a laptop with windows on it so for testing so i need to cross compile. There is an issue with sound which doesnt happen in wine and does in windows. I will debug that later today hopefully to get all sound drivers working in sdl. Currently only direct sound is working and its forced anyway so not really a immediate must fix issue.

fix cross compile for sdl2

---

src/burner/sdl/drv.cpp
src/burner/sdl/main.cpp
src/burner/sdl/media.cpp

MediaInit() and  MediaExit() take care of bVidOkay via AudSoundExit() and INT32 AudSoundInit() .  Same foes for the video side of things.

fix initialization

---

src/burner/sdl/config.cpp
src/burner/sdl/main.cpp

fixes https://github.com/finalburnneo/FBNeo/issues/1181 support paths should be set on config creation not and every  config save it appends paths as explained in there issue.

only append support path in linux when config file had not been created

---

src/burner/sdl/sdl2_gui_ingame.cpp

fixes finalburnneo/FBNeo#1177
thanks to @MistyDreams 
- Player's default inputs are now correctly listed independently of existing hardware defaults or not.
- Writing default inputs into ini file is no longer stuck in infinite loop.
- Saved defaults are applied in current game without the need to reset or restart.
- Fixed macro with longest name not working because last byte was missing.

SDL2: fix issues with default inputs menu

---

src/burn/drv/msx/d_msx.cpp
src/burn/drv/neogeo/d_neogeo.cpp

Updated to latest version found on author's repo (date from october 17, 2022).
Current version in fbneo: october 01, 2022.
.
Also, d_neogeo: 19yy
reverted to previous version as requested by taoenwen

d_msx: corrunner

---

src/burn/drv/galaxian/d_galaxian.cpp
src/burn/drv/sega/d_segas32.cpp
src/burn/drv/sega/d_sys18.cpp

d_sys18: Bloxeed (Japan, earlier) (FD1094 317-0139) [Brian Troha, The Dumping Union]
d_segas32: Soreike Kokology [SpinalFeyd]
d_galaxian: Fix Moonal2Init (gfx1 reload)

New working clones

---

src/burn/burn.h
src/burn/drv/neogeo/d_neogeo.cpp
src/burner/win32/ips_manager.cpp

Allow ips patches for single files larger than 16M (offset mode). Adjust the default neogeo's sma & pvc protection switch in ips mode

extend the functionality of ips

---

src/burn/devices/thready.h

Initially, the MSVC version did not support threading, so that the x86 binary version ran very slowly.
After adding msvc support, the following failures were found:
-------------------
*** Starting emulation of dfkbl - DoDonPachi Dai-Fukkatsu Black Label.
Alternative title is 怒首領蜂 大復活 (2010/1/18 BLACK LABEL).
BurnSetMouseDivider() @ 1
Cheat cpu-register INIT.
Init: our_event: 1324, wait_event: 2148
Proc: our_event: 1324, wait_event: 2148
--  sh3 init @ 102400000hz
Sh3SetClockCV1k:  102400000   tmu prescale 4
CPU-registry: sh3 cpu #0 ...
*** found speedhack for dfkbl
hack_ram: c002310  hack_pc: c1d1346
Init: our_event: 1328, wait_event: 1892
Proc: our_event: 1324, wait_event: 2148  <- Static variables in structures/classes are not synchronized correctly
* SoftFX initialised: using Plain …

thready - add support for msvc

---

src/burn/drv/neogeo/d_neogeo.cpp

Add samsho2 perfect hack
Changes
- Genan and Earthquake can now be grabbed when they are Crouched (bug fix).
- Ninja's can't infinite the opponent with their DP + K Throw attack (bug fix).
- Players cannot force the opponent to automatically execute BC (bug fix).
- Kuroko and Mizuchi are now playable (improvement).
- All 17 characters (including bosses) were balanced to improve the gameplay (improvement).
- Added hitboxes to all Stun and Block animations, they were missing (improvement).
- All Jumps in the game were modified for a better gameplay (improvement).
- The damage of several Attacks and Throws were balanced (improvement).
- Added a random select character feature, press start to random select (improvement).
- Added a Hit counter and a Dizzy text when characters get Dizzy …

d_neogeo: samsho2pe [Hack By Bear]

---

src/burn/drv/neogeo/d_neogeo.cpp

Latest version (2023-Mar-10 22h16 utc -3).
Changes:
Charllote can now combo with Close B or AB and Splash Fount. Jubei Close AB, the 2 slashes now connects in combo. Jubei Crouch AB, the 2 slashes now connects in combo. It can also be followed with DP. Wanfu special move now has longer hitboxes and it stays active for a longer time. Cham Cham paku paku is now faster.
Nicotine super pow is now faster, connect in hit combo bug remove select 2 mizuki crashed game

d_neogeo: samsho2pe

---

src/dep/macos/hid/AKGamepad.m
src/dep/macos/hid/AKGamepadManager.m

As `IOHIDDeviceRef`s are Core Foundation objects, calling `IOObjectRetain`/`IOObjectRelease` does nothing useful.

Use CFRetain/CFRelease on IOHIDDeviceRef

---

src/burn/drv/megadrive/d_megadrive.cpp

Latest version: 27b
HISTORY OF CHANGES (translated from russian).
Changes in version 27b:
1. If the hidden character selection is activated, then when choosing, the sounds of the Stryker machine gun and Nightwolf's ax are not played;
2. In 2v2 or 3v3 combat modes, if the hidden character selection is activated, then the cursor becomes visible for the next player and returns to its original position. In this case, the hidden character selection can be activated again;
3. Hidden character selection works only for the first battle;
4. In the options, the recovery range of the win counter has been expanded to 20.
----------
Changes in version 27a:
1. The Alt balance and Glitch jabs sections have been removed from the options. In their place, P1 wins and P2 wins have been added to restore the …

d_megadrive: add umk3osc

---

src/burn/drv/megadrive/d_megadrive.cpp

updated to version 28 (2023-Apr-23)
Changes:
1. Added Stage in the Dead Pool arena.
2. Added Stage in the arena of Kombat Tomb. As in Mk2, if you hold "Down", then the opponent will fall from the spikes. Or it can happen randomly (with a small probability).
3. Removed the ability to strike while standing up/sitting down in a block (the so-called 7th frame).
4. Fixed a bug with auto exit options.
5. Time spent in options increased to 5 minutes.
6. Added arena Tower Mk2 (2 layers).
7. Arena Jade's Desert skipped (removed, cut).
8. Reptile - dash hit limit. Blocked after 8 hits.
9. Rain - lightning hit limit. Blocked after 7 hits.
10. Cyrex - disable the flight timer after an air throw.
11. Sindel - hitlimit for flight. Blocked after 6 hits.
12. Hitlimit on relaunches. Blocked after 7 hits. …

d_megadrive: umk3osc

---

src/burner/gami.cpp

Modified line 500 for GameInpInitMacros(). Changed the conditional from checking for directional inputs, to checking if the player number was correct. This prevents the duplicate buttons from being added (ie. 2 P1 Weak Punch macros), while adding in the buttons like coin, start, and select.
Tested it out on a few games of different hardware, but I may still have missed something, since it almost seems like too simple a fix to not have been done already.

Added macros for start/select/coin, etc. Varies by hardware

---

src/burn/drv/spectrum/d_spectrum.cpp

d_spectrum: mightyff typo

---

src/burn/drv/neogeo/d_neogeo.cpp

Version v0.1 by GameHackFan
Select Screen changes:
- Punch buttons confirm the character you're selecting.
- Kick buttons change the character color.
- The game will draw the character sprite, so you can see the color being selected.
- Hold Start button to random select your character.
The game will randomize your character again everytime it goes back to the select screen.
- For Player vs CPU, the game will randomize the CPU color.
Game changes:
- For Player vs Player, the game will randomize the stage.
- Characters now have to take 5 hits on their Weak Spot to go dizzy.
- Hit on Weak Spot now does 25% more damage instead of 50%.
- Every character now has at least 1 Revenge Move.
- Revenge Moves can only be executed when you have less than 50% of your HP.
(don't trust the lifebar it is …

d_neogeo: add karnovre

---

src/burn/drv/neogeo/d_neogeo.cpp

2023-09-13:
Genjuro with a 70% damage combo that left all characters in a dizzy state, correct bug fix Galford buff 2 frames in "Mega strike dog go"
block defense medium and power, buff 1 frame, impact distance in sliding is greater, remaining in the same patterns stun! adjusted damage power attack sword all chars, reduce 2 points Sieger adjusted damage move special "Elephantglied", reduce 4 points Hanzo Buff, 6 frames in start move "fire dragon blast+AB", nerf 6 frames in recovery, move now connect in combo with medium attack
.
[movelist_png-img.zip](https://github.com/finalburnneo/FBNeo/files/12597184/movelist_png-img.zip)

d_neogeo: samsho2pe bugfix

---

src/burner/sdl/main.cpp

In the SDL/SDL2 port, `AppDebugPrintf()` (and thus `bprintf()`) is completely broken:
It passes a `va_list` to `printf` (!!) (instead of `vprintf`), causing all debug prints to output garbage data & occasionally segfaults.
(In particular, i was getting crashes whenever hiscore data was written to memory, because one of the debug messages happened to trigger a segfault)

SDL: Fix debug print function

---

src/burn/drv/neogeo/d_neogeo.cpp

crc "afaa4702" is from original rom ('whp').
correct is "b1348758".

d_neogeo: whpjq, correct CRC

---

src/burn/drv/neogeo/d_neogeo.cpp

New Update Version 1.8:
-----------------------------
Hurtbox all chars rebalanced in the air for so that when they collide someone gets hit Jumps with punch weak attacks from Sieger, Nicotine, Cham Cham are now blocked by jubei in special move "Shingatou blocked counter",buff! Medium punch attack short now blocked by jubei in special move "Shingatou blocked counter", buff! Hanzo infinite combo removed, jump right + CD attack cancels on ovehead, AB front cancel in mozuto, restarts the same loop, it worked in Earthquake, Sieger, Wanfu, Nerf! Special move Tsubame Rokuren consumes damage on defense in new version, buff! All chars execute command basic Race(Run), in original to cancel and attack in average of 12 or 7 frames, now cancel in 3 frames, buff! Hit counter now predicts the char in a …

d_neogeo: samsho2pe up to v1.8

---

src/burn/drv/neogeo/neo_run.cpp

When the arcade stick input switches in two opposite directions, there is a "empty" in the middle, but when the emulator uses the keyboard to switch in two opposite directions, the switch is often instantaneous. For example, when switching left and right on an arcade joystick, the actual input is left->empty->right. That is to say, there will be an empty direction when switching to the opposite direction! But when using keyboard input, the actual input is left->right, or left->left+right->right
The problem I discovered is that some game developers deliberately added matching for the empty direction input when checking command inputs. For example, kof98 rugby charactor's 24A, 246A, 222B, 28A/C. For the last 28A/C , I found that the actual command is 2N8+A/C, that is, a total of 3 …

Optimize the input problem of neogeo when using the keyboard

---

src/burn/drv/capcom/d_cps2.cpp

-sfa3xl: correct Init ('Cps2Init')
code moved to: below sfa3ce (normal roms area)
-sfz3mix: Updated to latest version v0.25 + correct Init base ('PhoenixInit').
-sfz3mix13: Correct Init ('PhoenixInit')
both code moved to: below Sfz3jr2d (phoenix roms area).

d_cps2: sfz3mix, sfa3xl corrections.

---

src/burn/drv/neogeo/d_neogeo.cpp

Removed bcd scaped command from, hanzo, kuroko and genan, moves scape from hanzo and kuroko It is now possible to use them in the middle of the game, new command in move list,  check!    Standardized Stun for attacks from above (jumping attack), stun medium for all chars! Fixed Kuroko talk before challenging to fight
Create new frame the char pick ups impulse before jumping, 2 frames for starting jump for all chars!

d_neogeo: samsho2pe v. 1.9

---

src/burn/drv/neogeo/d_neogeo.cpp

.p1: changed to non-watermarked file.
[mslug5fd-p1_ca50afdf_to_24ae2e4d.zip](https://github.com/finalburnneo/FBNeo/files/14275174/mslug5fd-p1_ca50afdf_to_24ae2e4d.zip)

d_neogeo: mslug5fd

---

src/burn/drv/capcom/d_cps1.cpp
src/burn/drv/capcom/d_cps2.cpp
src/burn/drv/neogeo/d_neogeo.cpp
src/burn/drv/pgm/d_pgm.cpp
src/burn/drv/pst90s/d_raiden2.cpp

d_cps1: wofdr20/kodsr/dinokr/captcmjy/bootlegs's QSound rebuilt drivers
d_cps2: ddsom1v4/ddsomudp/ddtoddp
d_pgm: kovphsqj/kovptstd/kovpxba/kovpxbb/oldsplusnr
d_neogeo: kof2ksp/kof97ce/mslugxcq/mslugxfs/mslug3cq/mslug3fs/kof95sr3/kof94nr2/aof2bhs/kof98eck/kof99pls/kof97rm/kf2k1ult
d_raiden2: zteammm/zteamys
https://github.com/finalburnneo/FBNeo/issues/1701
https://github.com/finalburnneo/FBNeo/issues/1690

update hack games (cps1/cps2/neogeo/pgm/raiden2)

---

src/burn/drv/capcom/d_cps2.cpp

Although a US version of hsf2pp already exists
Japanese (hsf2jpp) and Asian (hsf2app) versions have been added.
The hacker's name, Yumeji, and the date have been added to the ROM information
A script that can generate Roms in HTML can be downloaded from (Japanese website)
https://ux.getuploader.com/yumeji/download/21
screen shot

add hack hsf2jpp/hsf2app

---

src/burner/sdl/run.cpp

Just copied over the fixes from the win32 implementation of run-ahead. Tested with xmen6p and ninjak, and they seem to work as intended. Not sure if more thorough testing is needed, seeing as how it's been like this for a while. Please let me know if I'm missing anything, or if brought over anything extraneous.

Port over win32 runahead fixes to SDL

---

src/burner/burner.h
src/burner/gami.cpp
src/burner/win32/run.cpp

This PR adds input macros called "System Next State" and "System Previous State" to the Win32 build of FBNeo. These macros can then be bound to inputs, in the same manner as the existing "System Save State" and "System Load State" macros. The System Next State macro triggers the F11 hotkey, which selects the next save state slot, while the System Load State macro triggers the F8 hotkey, selecting the previous save state slot.
I got tired of having to take my hands off of my gamepad to press F8 and F11 to switch between save state slots. I wanted to be able to bind these shortcuts to buttons on my gamepad.
I've tested this by building the Win32 build, mapping the new macros to gamepad buttons, and verifying that they perform the expected actions while running a game. Each macro is only …

win32: Add input macros for System Next State and System Previous State

---

src/burn/drv/nes/d_nes.cpp
src/burn/drv/pre90s/d_pacman.cpp
src/burn/drv/pre90s/d_tsamurai.cpp

nes
d_nes - ghostsngoblins / ghostsngoblinsh: removed "NI 1.3" from header.
"NI 1.3 is the watermark of an old tool called NES Image converter." (by noone).
pre90s
d_pacman - mspacmane2: correct size for 'mpe6.6m' (checked in fbneo and rom manager).
d_tsamurai - alphaxz: changed "m660" to NULL, coz alphaxz is a parent ROM.

Some changes in nes/pre90s

---

src/burn/drv/neogeo/d_neogeo.cpp

removed 'Prevent color corruption when using Rugal' patch from combination.
in https://neorh.mattgreer.dev/kof94:
_"The Rugal color corruption fix and Team Edit Edition are not compatible with each other. Sorry about that."_

d_neogeo: kof94te

---

src/burn/drv/capcom/d_cps2.cpp

CPS2 added:
Hyper Street Fighter 2 (Japan) revision 040123 as hsf2j1. X-Men vs Street Fighter (Japan) revision 970113 as xmvsfj. ---------
Co-authored-by: Joe Forte
Info:
Hyper Street Fighter 2 (Japan) 040123 has two new roms (hs2j.03a and hs2j.04a) all other roms were identical. X-Men vs Street Fighter (Japan) 970113 also has two new roms (xvsj.03m and xvsj.04m) with all others being identical.
One oddity on X-Men vs Street Fighter is all of the program roms, besides the two new ones, are either mask roms or one time programable roms with the standard metallic Capcom stickers on them. Both boards were on battery (xmvsf had a date code of 96 on it) when I acquired them from Japan but have since been switched to using infinikeys. The rom labels appear to be legit Capcom labels but have …

d_cps2: add hsf2j1, xmvsfj [bugcutt / Joe Forte]

---

makefile.sdl
makefile.sdl2

When compiling SwapBytes.c (to be precise, cross compiling for armv7 was what I tested), fails with multiple errors like these:
`
src/dep/libs/lib7z/SwapBytes.c:598:47: error: expected ')' before ':' token
#define SWAP2_32_VAR(v)  asm ("rev16 %0,%0" : "+r" (v)); // for clang/gcc
`
As pointed by @barbudreadmon , SwapBytes.c is not needed ( https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/Makefile.common#L299-L314 ), so it should be safe to ignore.

Ignore SwapBytes.c (not used and has build error in SDL fork)

---

src/burn/drv/capcom/d_cps1.cpp
src/burn/drv/capcom/d_cps2.cpp
src/burn/drv/megadrive/d_megadrive.cpp
src/burn/drv/neogeo/d_neogeo.cpp
src/burn/drv/nes/d_nes.cpp
src/burn/drv/pre90s/d_toki.cpp
src/burn/drv/pst90s/d_powerins.cpp
src/burn/drv/snes/d_snes.cpp
src/burn/drv/taito/d_taitomisc.cpp

cps1 - add: sf2cebr, willowbr
cps2 - add: sfa3br (original game 'sfa3b' don't have portuguese language)
megadrive - updated: bssf2gq, add landstlkrmx
neogeo - add: rotdbr, aofbr, kof2k2br, kof2k3br
fds - add: dracuii t-eng, current rom renamed to dracuiij
pre90s - add: tokibr
post90s - add: powernbr, init fix by dinkc64
taito - add: rastsagabr
snes - add: blackthornetp, captsubasa4j, captsubasa5j, seikdens3j, seikdens3te (no header), sconflict, svgeo, yuuyuu2tp
renamed yu yu hakusho games. correct size for yu yu hakusho final.

Some changes in: MD / FDS / SNES / NG / CPS / TAITO / PRE-POST 90S

---

src/burn/drv/capcom/d_cps1.cpp
src/burn/drv/capcom/d_cps2.cpp
src/burn/drv/neogeo/d_neogeo.cpp
src/burn/drv/pst90s/d_powerins.cpp

post90s: in powernbr
capcom: in willowbr, correct hacking group for sfa3br
neogeo: in aofbr and rotdbr. add version number for kof2k2br, kof2k3br and rotdbr

pt-br hacks: fix typos

---

src/burn/drv/capcom/d_cps2.cpp

I found an inconsistency in japanese ddsom roms.
after checking cps2shock's site
current ddsomjr1 should be ddsomjr2 (no changes in labels). current ddsomjr2 should be ddsomjr1 (labels are: dd2j.03e /dd2j.04e / dd2.05e / dd2.06e).
This occurs in mame too.
\\\

d_cps2: fix ddsomjr1, ddsomjr2 romSets

---

src/burner/sdl/burner_sdl.h
src/burner/sdl/main.cpp
src/intf/video/sdl/vid_sdl2.cpp

In the SDL2 front end, the window is scaled to * 2 the game screen resolution. Whilst this works find for raster games on normal DPI monitors it doesn't work so well for :-
- raster games on HiDPI displays where the window appears too small.
- vector games where the window appears too big.
This change allows the user to specify a window scale at the command line. It defaults to * 2 for backward compatibility with the old version.
Full screen and window resizing via dragging is not affected by this change.

Add SDL2 set window scale command line option

---

src/burn/drv/spectrum/d_spectrum.cpp

the V2 is what we keep, v1 was bugged and fixed twice afterward.

Only have one MoonRN

---

src/burn/drv/capcom/cps.h
src/burn/drv/capcom/cps_run.cpp
src/burn/drv/capcom/cps_rw.cpp
src/burn/drv/capcom/d_cps2.cpp

This is extremely work in progress.
I only ported most of the Forgotten Worlds code from the CPS1 driver to CPS2, except dip switches. It compiles and runs, but it doesn't do anything.
I suppose we can choose to backport the spinner code from MAME, or just hook these into the rotation memory positions and go with it?
That's an area that's completely outside of my comfort zone, but if this code helps us move in the right direction, even if by a little bit, here it is!

First attempt at ecofght analogs

---

.github/workflows/nightly-release.yml

Thanks to the work done with @frangarcj in the #1996 we can finally put back the CI for generating the `.app` file.
Cheers

Put back nightly `MacOS` compilation

---

src/burner/macos/FBMainThread+Etc.mm

This avoids the crash when trying to open the menu if no game loaded
I will try to fix the remaining options in a separate PR

Fix crash when no game selected

---

src/burn/drv/snes/d_snes.cpp

d_snes.cpp: added "Double Dragon V - The Shadow Falls" (USA and Europe)
Notes: 
- I've followed the fact that you are usually using the USA games as parents, so the EUR version is clone of the USA one. 
- The ROM names are from MAME so history.xml works for both games.

d_snes.cpp: added "Double Dragon V - The Shadow Falls" (USA and Europe)

---

src/burn/drv/snes/d_snes.cpp

Notes:
- d_snes.cpp: Added support for "Super Ghouls'n Ghosts (Euro)"
- d_snes.cpp: Added support for "New Super Mario Land (HB, v1.5)"
- d_snes.cpp: Added support for "Teenage Queen (HB, v1.4)"
- d_snes.cpp: Corrected error in name of "Super Ghouls'n Ghosts" games

d_snes.cpp: SNES update

---

src/burner/sshot.cpp

The user can choose his own folders instead of the default ones for titles and previews images. 
I've changed the default fixed strings used for these folders ("support/titles" and "support/previews") by the global variables that contains the current folders in use (szAppTitlesPath and szAppPreviewsPath).

sshot.cpp: replace fixed titles and support strings by the global variables that contains them

---

src/burn/drv/pce/d_pce.cpp
src/burn/drv/snes/d_snes.cpp

d_snes.cpp: added the support to 5 SNES games (Euro region exclusives):
- F1 World Championship Edition (Euro)
- Might and Magic II - Gates to Another World (Euro)
- Super Dany (Euro, French)
- Waterworld (Euro)
- World Masters Golf (Euro)
d_pce.cpp: added the support to "Taito Chase H.Q. - Noise Fix (Hack)"
d_snes.cpp: rearrange a couple of misordered unlicensed games

Added the support to 5 SNES games (Euro region exclusives) and 1 TurboGrafx 16 hack

---

src/burn/drv/snes/d_snes.cpp

- Killer Instinct (Euro)
- Rise of the Robots (Euro)
- Rise of the Robots (Japan)
- SimEarth - The Living Planet (USA)
- Street Combat (USA)
- Omega Brazil '97 (USA) (Unl)
d_snes.cpp: renaming of some games, most of then labeled as "Alt", to reflect it's real origin (revision number, NSS, etc...)

d_snes.cpp: added the support to 6 new SNES games

---

src/burn/drv/nes/d_nes.cpp
src/burn/drv/snes/d_snes.cpp

d_snes.cpp: added the support to 7 new SNES/Famicom games:
- Columns (Japan, NP)
- Exhaust Heat (Euro)
- Super Bombliss (Japan)
- Super Tetris 2 + Bombliss Gentei Ban (Japan)
- Super Tetris 2 + Bombliss (Japan, Rev. 1)
- Super Tetris 3 (Japan)
- Tetris 2 (Euro)
d_nes.cpp: added the support to 2 new NES/Famicom games:
- Taito Chase H.Q. (Hack, English)
- Taito Chase H.Q. (Hack, English + Palette Fix)

d_nes.cpp, d_snes.cpp: added the support to several new games

---

src/burn/drv/snes/d_snes.cpp

- Disney's Aladdin (Euro, Spanish)
- Lost Vikings, The (Euro, Spanish)
- MechWarrior (USA)
- MechWarrior (Euro, Spanish)
- Super Battletank 2 (Euro, Spanish)
- Tiny Toon Adventures - Buster Busts Loose! (Euro, Spanish)
- Turn and Burn: No-Fly Zone (Euro, Spanish)
d_snes.cpp: updated "Emerald Dragon" Spanish translation v1.1 -> v1.2
d_snes.cpp: replaced "Super Big 2 (China) (Unl)" by another ROM more reliable
d_snes.cpp: corrected some ROMs names that included capital letters

d_snes.cpp: added the support to several SNES games from Euro Spain region

---

src/burn/drv/snes/d_snes.cpp

- Paladin's Quest (USA)
- Plashback (Hack, Spanish)
- Romance of the Three Kingdoms II (USA)
- Romance of the Three Kingdoms III - Dragon of Destiny (USA)
- Romance of the Three Kingdoms IV - Wall of Fire (USA)
- seaQuest DSV (USA)
- Super Mario All-Stars + Super Mario World (USA)
- Super Pinball - Behind the Mask (USA, Rev. 1)
- Super Stress Faijter II: The New Charnego's (Hack, Spanish)
- Super Troll Islands (USA)
d_snes.cpp: Changed source position and added translation note to "Justice Ninja Casey (World)" [Gab75]

d_snes.cpp: Added the support to 10 new SNES/Super Famicom games

---

src/burn/drv/megadrive/d_megadrive.cpp
src/burn/drv/pce/d_pce.cpp
src/burn/drv/snes/d_snes.cpp

d_snes.cpp: added the support to 8 new SNES/Super Famicom games:
- Syndicate (USA)
- Syndicate (Euro)
- Timeslip (USA)
- Timon & Pumbaa's Jungle Games (USA)
- Toys - Let the Toy Wars begin! (USA)
- Ultimate Fighter (USA)
- Wheel of Fortune (USA)
- Wheel of Fortune - Deluxe Edition (USA)
d_megadrive.cpp: added the support to 3 new Megadrive/Genesis games:
- Charnego Force II (Hack, Spanish)
- Kombate Mortá (Hack, Spanish)
- Tecmo Atleti (Hack, Spanish v2.0)
d_pce.cpp: added the support to 1 new PC-Engine game:
- Special Criminal Investigation - Noise Fix (Hack)

d_snes.cpp, d_megadrive.cpp, d_pce.cpp: added the support to several games

---

src/burn/drv/snes/d_snes.cpp

- Battle Grand Prix (Japan)
- Casper (Euro) (Absolute)
- Death and Return of Superman, The (Euro)
- Hook (Euro)
- Mr. Do! (Euro)
- Spawn (Euro)
- Spider-Man (Euro)
- Spider-Man and Venom: Maximum Carnage (Euro)
- Spider-Man - X-Men - Arcade's Revenge (Euro)
- Super Mario All-Stars + Super Mario World (Euro)
- Super Star Wars - Episode IV (Euro, Rev. 1)
- Super Star Wars - Episode IV (Japan)
- Super Star Wars - Episode V - The Empire Strikes Back (Euro, Rev. 1)
- Super Star Wars - Episode V - Teikoku no Gyakushuu (Japan)
- Super Star Wars - Episode VI - Return of the Jedi (Euro, Rev. 1)
- Super Star Wars - Episode VI - Jedi no Fukushuu (Japan)
- Teenage Mutant Hero Turtles: Tournament Fighters (Euro)
- Teenage Mutant Hero Turtles IV: Turtles in Time (Euro)
- U.N. Squadron (Euro)
- Venom & …

d_snes.cpp: added the support to several SNES/Super Famicom games from non USA region

---

src/burn/drv/snes/d_snes.cpp

blazeone -> blazeonj
Its a Japanese ROM (verified in no-intro DAT and snes9x).

d_snes.cpp - adj. in blazeone

---

src/burn/drv/nes/d_nes.cpp

adj. in maerchenveil - renamed to maerchenveilj and marked as clone
New games in the roster:
maerchenveil - english translation for maerchenveilj gokyuugamten - original game (japanese).
playtmprdise - english translation for gokyuugamten

d_nes.cpp - updates

---

src/burn/drv/capcom/d_cps1.cpp
src/burn/drv/capcom/d_cps2.cpp
src/burn/drv/megadrive/d_megadrive.cpp
src/burn/drv/pre90s/d_toki.cpp
src/burn/drv/sms/d_sms.cpp
src/burn/drv/taito/d_taitomisc.cpp

Fixed "published by" in willobr, tokibr, rastsagbr.
Fixed "GameName/comment" in sf2cebr, sfa3br
Fixed "Author" in md_alladinpt, md_chakanpt, md_shinfrc2pt. "Nenhum" means "None", isn't a group name.
Updated sms_alexkiddb (better version) and moved to hacks section.
Added sms_4lexkiddnw (Yes. is really 4lex, not Alex).

t-bra: some changes in cps/taito/pre90s/sms/megadrive

---

src/burn/drv/nes/d_nes.cpp

Add english translation
japanese ROMset renamed to ultra2j
crc patch`*`: f08f3854 -> 8f7f0352
f08f3854 Is CRC32 of fbneo ROM without header.
`*`Use this patch only if you didn't find ROM mentioned on translation site (8f7f0352).
[crc_patch.zip](https://github.com/user-attachments/files/21533523/crc_patch.zip)

d_nes.cpp - FDS: add ultra2

---

src/burn/drv/megadrive/d_megadrive.cpp

sgdk > 4mb always with ssf2 mapper

d_megadrive.cpp: knn school fighters repair

---

src/burn/drv/midway/d_xunit.cpp

@dinkc64 i'm not too happy with the default volume for revx and was trying to find a better compromise. What do you think of this ? It'll only increase volume on a fresh nvram with the default setting.

d_xunit.cpp: increase cmos's default volume

---

src/burn/drv/megadrive/d_megadrive.cpp
src/burn/drv/neogeo/d_neogeo.cpp
src/burn/drv/pce/d_pce.cpp
src/burn/drv/snes/d_snes.cpp

"Jurl (HB, v0.3c)" for NeoGeo
"Jurl (HB, v0.9b)" for PC-Engine
Also minor changes in same game version number for other systems for the sake of consistency

Added support to several "Jurl" game versions

---

src/burn/drv/msx/d_msx.cpp
src/burn/drv/snes/d_snes.cpp
src/burn/drv/spectrum/d_spectrum.cpp

d_snes.cpp: added the support to a bunch of european region titles:
"John Madden Football '93 (Euro)"
"NBA All-Star Challenge (Euro)"
"NBA Give 'n Go (Euro)"
"NBA Hang Time (Euro)"
"NBA Jam (Euro, Rev. 1)"
"NBA Jam - Tournament Edition (Euro)"
"NBA Live 95 (Euro)"
"NBA Live 96 (Euro)"
"NBA Live 97 (Euro)"
"Madden NFL '94 (Euro)"
"Madden NFL '95 (Euro)"
"NFL Football (Euro)"
"NFL Quarterback Club (Euro)"
"NFL Quarterback Club '96 (Euro)"
"NHL '94 (Euro)"
"NHL '95 (Euro)"
"NHL '96 (Euro)"
"NHL '97 (Euro, Rev. 1)"
"NHLPA Hockey 93 (Euro)"
"X-Kaliber 2097 (Euro)"
"Yogi Bear (Euro)"
"Yoshi's Cookie (Euro)"
"Young Merlin (Euro)"
"Zero the Kamikaze Squirrel (Euro, Rev. 1)"
"Zoop (Euro)"
d_spectrum.cpp: updated "Sorcery Island (Spanish)" to newest version
d_spectrum.cpp, d_msx.cpp: added the …

SNES/Super Famicom updates + misc updates

---

src/burn/drv/snes/d_snes.cpp

Added the support to a bunch of european region titles:
"Disney's The Lion King (Euro)"
"James Pond 3: Operation Starfi5h (Euro)"
"Looney Tunes Basketball (Euro)"
"Lost Vikings, The (Euro)"
"Lost Vikings II, The (Euro)"
"Magical Quest Starring Mickey Mouse, The (Euro)"
"Mega Man 7 (Euro)"
"Mega Man X (Euro)"
"Mega Man X2 (Euro)"
"Mega Man X3 (Euro)"
"Newman Haas IndyCar featuring Nigel Mansell (Euro)"
"Nigel Mansell's World Championship Racing (Euro, Rev. 1)"
"Ninjawarriors (Euro)"
"Olympic Summer Games (Euro)"
"On the Ball (Euro)"
"Operation Logic Bomb - The Ultimate Search & Destroy (Euro)"
"Outlander (Euro)"
"Pac-Attack (Euro)"
"Pagemaster, The (Euro)"
"Paperboy 2 (Euro)"
"Phalanx (Euro)"
"Pinball Dreams (Euro)"
"Pinball Fantasies (Euro)"
"Pink Goes to Hollywood (Euro)"
"Road Runner …

d_snes.cpp: SNES/Super Famicom update
