finalburnneo/FBNeo

src/license.txt
I can't find it anywhere else!
=> Link to old MAME licence

src/burn/drv/megadrive/d_megadrive.cpp
Changed many game genres
Organised Sonic clones
Other minor tweaks
=> Changes to genres and organised clones

src/license.txt
Since the project is reworking its license, it might be a good opportunity to remove this clause, it's pretty vague and i don't think that's something enforcable. If it is read verbatim it might even prevent the project from being usable at all (the project relies on directx, which is a bunch of dlls).
=> This clause doesn't really make sense

src/burn/drv/megadrive/d_megadrive.cpp
I found this new homebrew, it seems pretty well-made
=> Add Misplaced (megadrive)

src/burner/dat.cpp
I think it would be a good addition for people who want to trim non-working games from their romsets.
=> add driver status to dat files

src/burn/drv/neogeo/d_neogeo.cpp
=> Update some hacks to their latest versions.

src/burn/drv/capcom/d_cps1.cpp
It can be found in HBMAME's ROM sets.
=> Update wofchdx to final edition.

appveyor.yml, makefile, makefile.mamemingw, makefile.mingw, src/burn/drv/neogeo/d_neogeo.cpp
@dinkc64 Please remove the protections, thank you :)
=> Add kof97t from HBMAME.

src/burn/drv/pre90s/d_cclimber.cpp
Disable flipscreen for player2.
=> cclimber player2 flip fix

.github/workflows/macos.yml, projectfiles/xcode/Emulator.xcodeproj/project.pbxproj, src/burner/macos/FBMainThread.mm, src/burner/macos/burner_macos.h, src/burner/macos/main.cpp, src/burner/macos/main.h, src/burner/sdl/run.cpp, src/intf/audio/aud_interface.cpp, src/intf/audio/macos/FBAudio.h, src/intf/audio/macos/FBAudio.mm, src/intf/audio/macos/SDLAudioEngine.h, src/intf/audio/macos/SDLAudioEngine.m
This is a small update that removes dependence on SDL and includes a few changes that make the project buildable under GH CI.
=> macOS update

.github/workflows/ccpp.yml
Update for macOS build. Please note that this won't work without #160.  Thanks
=> macOS actions update

src/burn/drv/pgm/pgm_asic27a_type1.cpp, src/burn/drv/pgm/pgm_asic27a_type2.cpp, src/burn/drv/pgm/pgm_asic27a_type3.cpp, src/burn/drv/pgm/pgm_run.cpp
I tried backporting pgm clock adjustment stuff from https://neo-source.com/index.php?topic=3162.0
Merge if you think i got it right !
=> backport Jan's pgm clock ajustment

makefile.sdl2, src/burner/sdl/input.cpp, src/burner/sdl/main.cpp, src/intf/video/sdl/vid_sdl2.cpp
added command line switches.
Ive added a -joy switch this will map joystick to 0 to p1 without this switch it will use the default keyboard for player one.
also added a -vsync switch (this is for wonder boy to play properly). I plan on doing more work on the input but need these changes for testing.
=> updates for joysticks some other stuff

src/burn/burn.h, src/burn/driver.h, src/burn/snd/fm.c, src/burn/snd/fm.h, src/burn/snd/fmopl.h, src/cpu/arm7/arm7.cpp, src/cpu/mips3_intf.cpp, src/cpu/mips3_intf.h
I was thinking about doing those changes, is there any reason we shouldn't ?
1st commit fixes some declaration that would prevent 2nd commit to build.
=> Types sanitize

src/burn/drv/pgm/d_pgm.cpp
For detail of corrections, please visit https://www.ppxclub.com/forum.php?mod=viewthread&tid=695504&fromuid=150233. You may need a translation tool since that page is in Chinese.
=> Added an oldsplus hack which fixes many bugs.

src/burn/drv/pre90s/d_armedf.cpp, src/burn/drv/pre90s/d_galivan.cpp
- Fix refresh rate for some Nichibutsu games (see MAME)
- Fix DAC Sound pitch and gain of Armed Formation hardware, especially the pitch of orchestra hit of Armed Formation
=> Fix sound and refresh rate of some Nichibutsu games

src/burn/drv/galaxian/d_galaxian.cpp, src/burn/drv/galaxian/gal_stars.cpp
Compared to PCB and latest MAME
- Fixed Jump Bug background stars
- Before fix is like Scramble, but correct is Galaxian.
- Fixed PSG clock of Jump Bug hardware
=> Fixed Jump Bug stars and sounds

src/burn/drv/pre90s/d_terracre.cpp
Kid no Hore Hore Daisakusen, Soldier Girl Amazon, Terra Cresta
- Fixed one frame lag in sprite and BG moving. Modified in the same way as the latest MAME.
=> d_terracre.cpp : Fixed sprite lag

src/burner/sdl/main.cpp
I have update the code there no games are listing though im not sure if this is for things to come if its just not working properly let me know and ill look into it more thanks
=> update dat file creation for nes and fds dor sdl and sdl2

src/burn/drv/konami/d_finalzr.cpp, src/burn/drv/pre90s/d_skyfox.cpp
Sky Fox (Exerizer)
- Added Japanese version support
- Added support for P2 start button
- Fixed background is completely different from PCB (same fix as MAME 0.217)
- Change refresh rate and sound clock based on MAME
Finalizer
- Fixed incorrect score display position
=> Sky Fox (Exerizer) and Finalizer some fixed

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj, projectfiles/xcode/Emulator/Controllers/FBLauncherController.m, projectfiles/xcode/Emulator/Info.plist, projectfiles/xcode/Emulator/Views/FBRomSetStatusAsNSImage.m, src/burner/macos/FBScanner.h
Fixed Stunt Air build
Added cache file versioning
=> Support for Stunt Air

src/burn/drv/neogeo/d_neogeo.cpp
With the edited path now, errors out when I'd try editing manually.
This is for a small handful of character hacks for Super Dodgeball, Magical Drop III, the two Real Bout Fatal Furies, and Waku Waku 7, more will come later but I have to set those up first.
=> Neo Geo Hacks

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj
Fixes build on macOS re: Megadrive EEPROM addition.
=> MD EEPROM fix

src/burn/drv/capcom/d_cps1.cpp
to fix the boss not coming out on 1st stage.
Patches are ripped from RAM with running FBAS.
=> Patches for wofh & wofha

src/burn/drv/pre90s/d_skyarmy.cpp
New dump of the main CPU to fix game breaking problems in level 3
=> skyarmy: Fix bitrot, makes the game fully playable [O. Galibert]

src/burn/drv/neogeo/d_neogeo.cpp
0.157: DsNo redumped/verified Fight Fever romsets. Added new 060-s1.s1 rom.
=> FBN already supports the redumped rom

src/burn/drv/dataeast/d_dblewing.cpp
=> New working clone Double Wings (Asia)

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj
=> Monday driver extravaganza

makefile.pi
Fixes `makefile.pi` build (long overdue)
=> Fixed pi build

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj
From commits 403f2e4 and eb06c9c
=> Added drivers

src/burn/drv/sega/d_segae.cpp
=> Fix a little mixup with the parent / clone naming

src/burn/drv/sega/d_segae.cpp
=> Try that again :)

src/burn/drv/konami/d_rockrage.cpp, src/burn/drv/pst90s/d_gstream.cpp
Need help for lethal and asterix....
=> Endianized gstream and rockrage 

src/burn/drv/neogeo/d_neogeo.cpp
Added support code of The King of Fighters '97 (Practice Mode) to d_neogeo.cpp
=> kof97pm support

src/burn/devices/c169.cpp, src/burn/drv/pst90s/d_namcos2.cpp
Tested all:
// assault
// burnforc
// cosmogng
// dsaber
// mirninja
// valkyrie
// ordyne
// phelious
// rthun2
// marvland
// metlhawk
// kyukaidk
// sws92,93
// sgunner
// sgunner2 (needs old mcu)
// dirtfoxj
// finehour
// luckywld
=> namcos2 Big Endian Fix

src/burn/drv/sega/sys16_gfx.cpp
Finally Galaxy Force 2 works correctly on PS3!!!!
=> Sega sys16_gfx Big Endian fix

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/midway/d_wunit.cpp, src/burn/drv/neogeo/d_neogeo.cpp
cps1: wofjdr upto ver. 20200913
wunit: umk3uc upto ver. 20200915
neogeo: add homebrew nsmb (Neo Super Mario Bros Demo!)
=> Hack games upgrade & add homebrew game

src/burner/burner.h, src/burner/gami.cpp, src/burner/win32/inpd.cpp
Solve the problem that Windows API causes compilation errors on sdl2
=> macro & autofire: Fix for sdl2

src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/nes/d_nes.cpp
d_nes.cpp: add 2 nes chinese Translations
d_neogeo.cpp: re-add the original version of kof97ae
=> d_nes.cpp & d_neogeo.cpp: add games

src/burner/win32/main.cpp
fbneo <game> [-listinfo|-w|-a|-r <width>x<height>x<depth>|-p]
-i = Start from the game of configured ips
Examples:
fbneo sfa3 -r 800x600x32 -p
fbneo sfa3 -w -p
fbneo sfa3 -p
=> main.cpp: win ui cmdLine add "-p" switch

src/burn/drv/megadrive/d_megadrive.cpp, src/burn/drv/pgm/d_pgm.cpp
- kov2:
Fixed the bug that Xia Houyuan didn't move and the plot didn't advance after 107 version of recruiting Xia Houyuan
=> d_pgm.cpp: update kovplus2020tx to ver. 20201010

src/burn/drv/pgm/d_pgm.cpp
update oldsdsgl to ver. 20201009
=> d_pgm.cpp: rename zerofxzdsgl to oldsdsgl

src/burn/drv/megadrive/d_megadrive.cpp
Translation project: https://romhacking.it/project/view/id/364
=> Wonder Boy in Monster World - Italian translation

src/burn/drv/megadrive/d_megadrive.cpp
=> Megadrive - Comix Zone (Hack, Italian) added.

src/burn/drv/megadrive/d_megadrive.cpp
=> Megadrive - Tecmo Cup (Hack, Italian) added.

src/burn/drv/megadrive/d_megadrive.cpp
=> Megadrive - Alien Soldier (Hack, Italian) added

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj, src/burn/drv/spectrum/d_spectrum.cpp
Updated d_spectrum so it compiles
=> Removed missing Speccy files from project

src/burn/drv/megadrive/d_megadrive.cpp
=> Megadrive - Streets of Rage 2 (Hack, Italian) added

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/neogeo/d_neogeo.cpp
=> d_neogeo.cpp: kof2k2plus 20201022

src/burn/drv/pce/d_pce.cpp
=> SGX - Chris Covell's R-Type unfinished hack added

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj, projectfiles/xcode/Emulator/Base.lproj/About.xib, projectfiles/xcode/Emulator/Info.plist
[Binary](https://github.com/fbn-mac/FBNeo/releases/tag/macos-v1.0.0.0)
neokobe
=> Version 1.0.0.0 release

src/burn/drv/pce/d_pce.cpp
=> SGX -  Homebrew conversion of RTA2 added

src/burn/drv/capcom/d_cps1.cpp
=> cps1: captcommr1pwx update 20201105

src/burn/drv/pst90s/d_kaneko16.cpp
Reverts finalburnneo/FBNeo#573
=> Revert "d_kaneko16.cpp - Complete Big Endian fix"

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/midway/d_wunit.cpp, src/burn/drv/pgm/d_pgm.cpp
d_pgm.cpp: update oldsdsgl to 20201123 version
d_wunit.cpp: update umk3uc to 20201122 version
=> d_cps1.cpp: update dinods to 20201121 version

src/burner/sdl/run.cpp, src/burner/sdl/sdl2_gui.cpp, src/burner/sdl/sdl2_gui_ingame.cpp, src/intf/video/sdl/vid_sdl2.cpp, src/intf/video/sdl/vid_sdl2opengl.cpp
=> SDL2 Improvements

src/burner/sdl/burner_sdl.h, src/burner/sdl/main.cpp, src/burner/sdl/run.cpp, src/burner/sdl/sdl2_gui.cpp, src/burner/sdl/sdl2_gui_common.cpp, src/burner/sdl/sdl2_gui_common.h, src/intf/video/sdl/vid_sdl2.cpp, src/intf/video/sdl/vid_sdl2opengl.cpp
Add ALT-ENTER : switch between window/fulscreen or fullscreen/window
=> SDL2: add switch window/fullscreen

src/burner/sdl/burner_sdl.h, src/burner/sdl/main.cpp, src/burner/sdl/run.cpp, src/burner/sdl/sdl2_gui.cpp, src/burner/sdl/sdl2_gui_common.cpp, src/burner/sdl/sdl2_gui_common.h, src/intf/video/sdl/vid_sdl2.cpp, src/intf/video/sdl/vid_sdl2opengl.cpp
Reverts finalburnneo/FBNeo#608
=> Revert "SDL2: add switch window/fullscreen"

src/burn/drv/midway/d_wunit.cpp, src/burn/drv/neogeo/d_neogeo.cpp
d_wunit.cpp: update umk3uc to 20201201 version
=> d_neogeo.cpp: update nsmb to Demo 0.01

src/burner/sdl/burner_sdl.h, src/burner/sdl/main.cpp, src/burner/sdl/run.cpp, src/burner/sdl/sdl2_gui.cpp, src/burner/sdl/sdl2_gui_common.cpp, src/burner/sdl/sdl2_gui_common.h, src/intf/video/sdl/vid_sdl2.cpp, src/intf/video/sdl/vid_sdl2opengl.cpp
=> SDL2: add ALT-ENTER to switch mode fullscreen/window

src/burn/drv/capcom/d_cps1.cpp
This time it won't give weird stats
=> SF 2 Mix dipswitches

src/burn/drv/neogeo/d_neogeo.cpp
You can find this hack in the lastest HBMAME ROM sets.
=> Add kof98ult.

src/burn/drv/capcom/d_cps1.cpp
sf2mix updated to 0.98c version [18:13 15/12/2020]
=> Update d_cps1.cpp [sf2mix 0.98c]

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/midway/d_wunit.cpp, src/burn/drv/nes/d_nes.cpp, src/burn/drv/pgm/d_pgm.cpp
d_wunit.cpp: update umk3uc to 20201204 version
=> d_cps1.cpp: update dinods to 20201202 version

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj, projectfiles/xcode/Emulator/Info.plist
re: 7b0dfff9b351c2400eab7660f8fe767a9c8c2e71
Happy holidays!
=> Updated drivers; updated cache version

src/burn/drv/pst90s/d_pushman.cpp, src/burn/drv/pst90s/d_sandscrp.cpp, src/burn/drv/pst90s/d_shadfrce.cpp
Diff patch files for Retroarch and libretro/FBNeo worked fine.
The show CAN go on.
=> d_pushman.cpp - Big Endian Fix

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj, projectfiles/xcode/Emulator.xcodeproj/xcshareddata/xcschemes/Emulator.xcscheme, projectfiles/xcode/Emulator/FinalBurn NeoDebug.entitlements, projectfiles/xcode/Emulator/Info.plist, src/dep/libs/libpng/arm/arm_init.c, src/dep/libs/libpng/arm/filter_neon.S, src/dep/libs/libpng/arm/filter_neon_intrinsics.c, src/dep/libs/libpng/arm/palette_neon_intrinsics.c
This PR does a couple of things:
* Adds LSA Squad drivers
* Adds ARM dependencies for libpng, so that the ARM release can compile (note: ARM builds are still unsupported, since I have no hardware to verify functionality)
* Updates to latest Xcode recommendations
* Enables Hardened Runtime for Release build (for upcoming signed Release builds)
=> LSA Squad driver support & miscellany

src/burn/drv/cave/d_korokoro.cpp
@crystalct can you check if ok for you ?
=> d_korokoro.cpp - Big Endian fix

src/burn/drv/midway/d_wunit.cpp
umk3uc updated to version 2020-12-26 - 13h25 utc-3 26/12/2020
=> Midway: Updated umk3uc

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/pgm/d_pgm.cpp
d_cps1.cpp: update wofjdr to 20201227 version
d_pgm.cpp: update oldsdsgl to 20201231 version
=> d_cps1.cpp: update dinods to 20201231 version

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj
Fixes macOS build by adding missing headers
=> Added biquad.h, downsample.h

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj
Updates CPU code to new 340x0 core.
=> tms340x0 core switch

projectfiles/xcode/Emulator/Views/FBScreenView.mm
Fixes #667 - Adds high-dpi display rendering support (retina, 4k, etc)
=> Added retina/hi-dpi display support

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj, projectfiles/xcode/Emulator/Info.plist
=> Added artmagic & exterm

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/midway/d_wunit.cpp, src/burn/drv/pgm/d_pgm.cpp
d_pgm.cpp: update kovplus2020tx to 20210128 version
d_cps1.cpp: update dinods to 20210204 version
d_cps1.cpp: update wofjdr to 20210201 version
d_wunit.cpp: update umk3uc to 20210209 version
=> d_pgm.cpp: update oldsdsgl to 20210111 version

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/pgm/d_pgm.cpp, src/burn/drv/pst90s/d_seta2.cpp
d_pgm.cpp: add kovshpd3dw (GOTVG 20201218 version)
d_cps1.cpp: add dinosyn (GOTVG 20210131 version)
d_seta2.cpp: add grdianslbs (GOTVG 20210211 version)
d_seta2.cpp: add grdianslbss (GOTVG 20201201 version)
d_seta2.cpp: update grdianssy to 20201228 version
=> d_neogeo.cpp: add kof2000sp (Hack by GSC2007 & EGCG)

src/burner/win32/run.cpp
A user with hand disability asked if we could move that key to make things nicer for keyboard users. Is that change fine for everyone ?
=> move kaillera chat key

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/midway/d_wunit.cpp
=> d_cps1.cpp & d_wunit.cpp:

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj
The previous PR did not fix the broken build, my apologies. Here's a fix.
=> Fixed broken build

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/midway/d_wunit.cpp, src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/pgm/d_pgm.cpp, src/burn/drv/pst90s/d_seta2.cpp
d_wunit.cpp: update umk3uc
d_cps1.cpp: update dinosyn
d_seta2.cpp: update hack games
d_pgm.cpp: update hack games
d_neogeo.cpp: update kof98pfe
=> update hack games

src/burner/sdl/sdl2_gui.cpp
HARDWARE_PREFIX_FDS
HARDWARE_PREFIX_CHANNELF
Add GBF_ADV genre
=> SDL2 GUI: add missing filters

src/burn/drv/capcom/d_cps2.cpp
ssf2tnl updated to version 0.5
11/06/2021 - 22h24 (utc -3)
=> CPS2: updated ssf2tnl

src/burn/drv/capcom/d_cps1.cpp
sf2mix updated to v1.0
23/06/2021 11h51 (utc -3)
=> CPS1: sf2mix 1.0

src/burn/drv/spectrum/d_spectrum.cpp
octuktty: Minor changes in name capitalization
17h46 (utc -3)
=> Spectrum: octuktty fix

src/burn/drv/megadrive/d_megadrive.cpp
sonic3p1 and md_sonic3p2: Added ".bin" in filename.
2021/07/10 ~ 21h08 (utc -3)
=> Megadrive: minor changes in sonic3p1/p2

makefile, makefile.mingw, src/intf/audio/win32/aud_dsound3.cpp, src/intf/audio/win32/aud_xaudio2.cpp, src/intf/input/win32/inp_dinput.cpp, src/intf/video/win32/vid_d3d.cpp, src/intf/video/win32/vid_ddraw.cpp, src/intf/video/win32/vid_ddrawfx.cpp, src/intf/video/win32/vid_directx9.cpp, src/intf/video/win32/vid_directx_support.cpp
Added this is hand if people want to compile and use on linux. Feel free to add or not just came in handy for me to test the lua issue as i dont have a windows build env
=> add mingw cross compile

src/burn/drv/capcom/d_cps2.cpp
Spf2t Color blind Hack, by TrashBoat
2021/08/29 ~ 22h07 (utc -3)
=> CPS2: spf2tcb, new version

src/burn/drv/capcom/d_cps2.cpp
Added Super Puzzle Fighter II X' Balanced Patch, hack by KScl
2021/09/09 ~ 15h34 (utc -3)
=> CPS2: Added spf2xpri

src/burn/drv/spectrum/d_spectrum.cpp
advconta / advcontb: minor change in rom name capitalization.
=> Spectrum: advconta/b fix

.github/workflows/AutoBuild.yml
Hi,
We've been speaking about this for such a long time ... Here is the PR to unify linux + Windows builds in a single github action. This is quite basic for now and can be much improved. I haven't removed the previous CI files, I leave it up to you.
=> Rewrite CI

src/burn/drv/spectrum/d_spectrum.cpp
Minor change in rom name capitalization.
=> Spectrum: lava16k fix

projectfiles/visualstudio-2019/fba_vs2010.vcxproj, projectfiles/visualstudio-2019/fba_vs2010.vcxproj.filters, src/burner/win32/run.cpp, src/burner/win32/scrn.cpp, src/burner/win32/scrn.h
This pull request adds hotkeys for the lua console  (alt + key described). This should allow less clicking for lua script developers and better workflow.
Was not sure about updating other VS projects for the scrn.h header file or whether this was the best way to approach this feature.  My CPP knowledge isn't the best and this is a complex code base. Let me know how I should fix things if they aren't correct and I will do my best!
=> adds hotkeys for lua console

makefile.sdl2, src/intf/video/sdl/vid_sdl2opengl.cpp
SDL2 doesnt use scalers, so can reduze bin ;-)
=> SDL2: delete scalers from build

src/burner/sdl/sdl2_gui.cpp
- add SDL_CONTROLLER_AXIS_LEFTX to move = +/- 10
- add SDL_CONTROLLER_BUTTON_DPAD UP/DOWN/LEFT/RIGHT control
- add button START (same as A)
- add SDL_CONTROLLER_BUTTON_LEFTSTICK / SDL_CONTROLLER_BUTTON_RIGHTSTICK = +/- game per screen
=> SDL2: put CONTROLLER to SDL_pollevent

src/burner/sdl/main.cpp, src/intf/input/sdl/inp_sdl2.cpp, src/intf/video/sdl/vid_sdl2.cpp, src/intf/video/sdl/vid_sdl2opengl.cpp
- main.cpp: no more need BurnLibExit and SDL_Quit because always exit on "Bye" function called by aexit
- main.cpp: add SDL_INIT_GAMECONTROLLER
- vid_sdl2.cpp: clean and put printf into FBNEO_DEBUG
- clean and put printf into FBNEO_DEBUG
- inp_sdl2.cpp: if use SDL_GameControllerOpen, need SDL_GameControllerClose
=> SDL2: enhanced

src/burner/sdl/main.cpp
If a per game config exists, do not overwrite.
-joy will still overwrite.
=> Do not overwrite pergame config

src/burn/drv/capcom/d_cps1.cpp
=> CPS1: sf2mix 1.2

projectfiles/visualstudio-2019/fba_vs2010.vcxproj, projectfiles/visualstudio-2019/fba_vs2010.vcxproj.filters, src/burn/drv/midway/d_wunit.cpp, src/burn/drv/nes/d_nes.cpp
add: d_powerbal.cpp
add: d_bloodbro_ms.cpp
add: vid_effect.h
add: vid_effect.cpp
=> Add: VS2019 - 2022 support

src/dep/scripts/build_details.cpp
=> Visual Studio 2019 - 2022 Support

src/burn/drv/capcom/d_cps2.cpp, src/burn/drv/nes/d_nes.cpp, src/burner/win32/systeminfo.cpp
1、systeminfo.cpp：fix some bug (winver)
2、d_cps2.cpp: ssf2tnl upd to v0.6 (beta) - Born2SPD
3、d_nes.cpp: add lupinsansc & upd heberekec
=> upd: systeminfo; cps2; nes

src/burn/drv/pre90s/d_pacman.cpp
Updated alienres to the latest download from website
=> Updated alienres

src/burner/win32/systeminfo.cpp
=> win32: x86 - calculate memory accurately

src/burn/drv/dataeast/d_dec0.cpp
It's my first attempt at this - thanks @barbudreadmon for the guidance with the DIP switches.
I added right-stick control support to Midnight Resistance and Heavy Barrel, two games with dial controls for shooting.
The way I did it is potentially sub-optimal - would definitely welcome feedback and guidance in regards to the actual code - but it works. I know this is an area that @dinkc64 worked a lot on in the past, reading the multiple comments in the code, so I'd definitely heed your guidance and recommendations as well :)
If this ends up being accepted and approved, I'll happily attempt something similar for Ikari Warriors (different driver, so I left it alone for now until I understand the best way to do this with you all).
Thanks and keep up the great work!
EDIT: this hasn't been …
=> Add Right-Stick support for MidRes, HBarrel

src/burner/win32/systeminfo.cpp
=> upd win32 systeminfo

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/pgm/d_pgm.cpp, src/burn/drv/pst90s/d_seta2.cpp
seta2
-----------
grdianslbs
grdianslbss
grdianske
grdianssy
cps1
-----------
captcommr1pwx
dinods
dinogae
dinosyn
pgm
------------
kovplus2020tx
=> upd arc hacks

projectfiles/visualstudio-2019/fba_vs2010.vcxproj
Enable the [record avi] menu
[Before update]
[After update]
=> update vc project 2019

src/burn/drv/megadrive/d_megadrive.cpp
Pac-Man 2 - The New Adventures (T-Chi, v1.1)
Phantasy Star - The End of the Millennium (T-Chi, v1.6)
=> d_megadrive.cpp : add t-chi games

src/burn/drv/megadrive/d_megadrive.cpp
https://github.com/andwn/cave-story-md/releases/tag/v0.8.0
update en
add ja & zh
=> cavestory : update to v0.8.0

projectfiles/visualstudio-2015/fba_vs2010.vcxproj, projectfiles/visualstudio-2015/fba_vs2010.vcxproj.filters, projectfiles/visualstudio-2015/fba_vs2015.sln, projectfiles/visualstudio-2019/fba_vs2010.vcxproj, src/burn/drv/nes/d_nes.cpp
[1] vs2019 - Enable [avi recorder] (debug / release | x64 / x86)
[2] vs2015 - Sync vs2019
[3] nes - add / update t-chi games
=> update vs2015 / 2019 & nes

projectfiles/visualstudio-2015/fba_vs2010.vcxproj, projectfiles/visualstudio-2022/building.txt, projectfiles/visualstudio-2022/fbneo_vs2022.sln, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj.filters, src/dep/vs2010/pre2022.bat
[1] add vs2022 project (x86 with nasm)
[2] fix some bugs (vs2019)
[3] sync vs2015
[4] Correct identification of x86 / x64
[5] about / system info - unicode
=> update msvc project

src/burn/drv/pst90s/d_seta.cpp
So, your comment on `Joy2Rotate`
// ugly code, but the effect is awesome. -dink
is the understatement of the year. Wait until you see `Joy2Rotate16`. :)
I followed your initial pointers and then fumbled my way through it, lots of printfs, a bit of trial and error. Thanks for kicking me off in the right direction :)
Now, this seems to work. It plays "nicer", to be honest. I am not 100% satisfied with parts of the code (it works, but doesn't feel as elegant as _I feel it should be_), and with the gameplay handling of the analogs-to-16-directions feel - I tried different granularity of intervals, but couldn't find one that feels _just right_. The current one seems to work well (it's dividing by 32 rather than 31, I am depending on the dead zone to work as intended, but let me know if that's …
=> Add 16-direction analog support to calibr50

src/burn/drv/spectrum/d_spectrum.cpp
romnames in lower case (hercslayer / shoveladv)
=> Spectrum: fixed capitalization

src/burn/drv/msx/d_msx.cpp
=> MSX: mtriton

src/burn/drv/neogeo/d_neogeo.cpp
Updated to version beta 3 (2022-03-12)
=> Neogeo: teot

src/burn/drv/capcom/d_cps2.cpp
=> CPS2: sfz3mix

src/burn/drv/neogeo/d_neogeo.cpp
added "kof2001Init" instead "kof2k1rpInit".
=> kof2k1rp, minor changes

src/burn/drv/pgm/d_pgm.cpp, src/burn/drv/pgm/pgm_run.cpp
=> pgm hack game kov2dzxx [Creamymami (FBAs)]

src/burn/drv/capcom/d_cps2.cpp
=> CPS2: sfz3mix 0.10

src/burn/drv/pre90s/d_alpha68k2.cpp
Adding analog and 12-directions support for timesold.
The previous changes had made it work assuming it had 8-directions only, but [a user pointed out it's supposed to be 12 instead](https://retropie.org.uk/forum/topic/32281/lr-fbneo-new-right-stick-controls-for-several-rotary-games/4?_=1649970605485). 
@barbudreadmon this follows the same naming convention as calibr50 for the right analog stick which might require changes in `retro_input.cpp` when porting it over to the libretro fork for it to be automatically configured.
In my case, I simply added to `GameInpSpecialOne` the following:
```
// Time Soldiers
if ((parentrom && strcmp(parentrom, "timesold") == 0) ||
(drvname && strcmp(drvname, "timesold") == 0)
) {
if (strcmp("Aim X", description) == 0) {
GameInpAnalog2RetroInpAnalog(pgi, …
```
=> Add 12-direction analog support for timesold

src/burn/drv/midway/d_wunit.cpp, src/burn/drv/nes/d_nes.cpp
nes: add T-Chi games (nes_doubldraiiisc; nes_downtnekmonc;  nes_missiimpc)
wunit: Revert 2021/07/20 FBNeo special edition
=> update : d_nes.cpp & d_wunit.cpp

src/burn/drv/nes/d_nes.cpp
=> nes add some t-chi games

src/burn/drv/capcom/cps.cpp, src/burn/drv/capcom/cps.h, src/burn/drv/capcom/d_cps1.cpp
=> cps-1 sf2amf10 is working now

src/burn/drv/capcom/d_cps1.cpp
Cadillacs and Dinosaurs Readjusted Hack v1.0
=> d_cps1: Added dinore

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/megadrive/d_megadrive.cpp, src/burn/drv/neogeo/d_neogeo.cpp
Export s1 from c7 & c8 and find that it is consistent with the external s1, so the external s1 is deleted.
=> d_neogeo: update kof2k2plus

src/burn/drv/capcom/d_cps1.cpp
=> d_cps1 : add Sangokushi II (Asia, bootleg, set 2)

src/burn/drv/galaxian/d_galaxian.cpp
sync mame ：added olibug / mooncreg2
sync dipsw ：mooncreg2 (MooncrslDIPList)
Oli Bug (Jump Bug bootleg)
Moon Cresta (Electrogame S.A. Spanish bootleg, set 2)
=> update d_galaxian.cpp :

src/burn/drv/capcom/d_cps2.cpp
=> Cps2: sfz3mix v0.11

src/burn/drv/megadrive/d_megadrive.cpp, src/burn/drv/nes/d_nes.cpp
[1-0] nes : 
[1-1] 
Captain America and the Avengers (T-Chi) - [LSP Team]
[1-2] Flintstones, The - The Rescue of Dino & Hoppy (T-Chi) - [HHNM Team]
[1-3] Jackal - Endless Mission (v1.2) - [HHNM Team - ZENG GE]
[2-0] megadrive :
[2-1] Ghosts'n Goblins (HB, Ver. 2021-11-01) - [Fabrice Fernandez]
=> update : nes / megadrive

src/burn/drv/pst90s/d_nmk16.cpp, src/burn/drv/toaplan/d_batsugun.cpp, src/burn/drv/toaplan/d_dogyuun.cpp
[1] d_batsugun.cpp : added Batsugun (older, set 2) [batsugunc]
[2] d_dogyuun.cpp : added Dogyuun (oldest set) [dogyuunb]
[3] d_nmk16.cpp : added Thunder Dragon (bootleg with Raiden sounds, unencrypted) [tdragonb3]
=> update : toaplan / pst90s

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/neogeo/neo_run.cpp, src/burn/drv/nes/d_nes.cpp, src/burn/drv/pgm/d_pgm.cpp, src/burn/drv/pst90s/d_nmk16.cpp
[cps-1] update wofjdr to 20220507
[neo_run] Remove unused variable
[nes] add / update T-Chi games
=> update cps-1 / neogeo / nes

src/burn/drv/neogeo/neo_run.cpp
finally got around to fixing this issue that i previously described on the libretro forums over here: https://forums.libretro.com/t/strange-behavior-in-mame-lag-control/35082/43
this patch changes the order of emulated scanilnes from [0-264) to [248, 264) followed by [0, 248). this reduces latency for any games that poll input shortly after vblank as well as reduces the variance of response times for games that oscillate between emulated frame slices under the current configuration, as the metal slug games do. ex: metal slug 2/x will now always (provided the game is not undergoing slowdown) show a response when frame stepping the emulation within 3 to 4 frames rather than 3 to 5 frames
i have another branch with the same fix that can be toggled on/off with a #define variable along with …
=> Reduce latency by adjusting emulated frame slice boundary

src/burn/drv/megadrive/d_megadrive.cpp
=> d_megadrive: Added jtoblivion

src/burn/drv/capcom/d_cps2.cpp
Cyberbots Access Mod
info: https://pastebin.com/VbCDxfw0
same as PR#921, but now with correct crc (*.key)
=> d_cps2: Add cybotsam

src/burn/drv/neogeo/d_neogeo.cpp
ips (base : mslug4a)
[mslug4a.zip](https://github.com/finalburnneo/FBNeo/files/8698460/mslug4a.zip)
=> d_neogeo.cpp : mslug4a up to 20210826

src/burn/drv/neogeo/neo_run.cpp
Fixed ips enabled, cmc decoding exception when 6C ROMs
=> neo_run.cpp : Fixed bug when using ips

src/burn/drv/neogeo/d_neogeo.cpp
test set:
https://drive.google.com/file/d/1rrMjDMCEZlgLsNipOk7p8TQ-HlGupVMQ/view?usp=sharing
=> d_neogeo.cpp : add mslughb [hb]

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/capcom/d_cps2.cpp
striderfix: Graphic and music fixes hack
sfz3mix: updated to version 0.12 (latest)
=> d_cps1: add striderfix

src/burn/burn.h, src/burn/drv/neogeo/d_neogeo.cpp, src/burner/qt/burner_qt.h, src/burner/qt/main.cpp, src/burner/sdl/ips_manager.cpp, src/burner/win32/ips_manager.cpp
Some neogeo ips require sma/pvc protection, some do not, create a flag (#define __PROTECTION__) in xxx.dat to identify if the driver needs to enable protection.
Test ips (base : mslug3):
-----------------
require protection:
[mslug3.zip](https://github.com/finalburnneo/FBNeo/files/8715335/mslug3.zip)
-----------------
un-require protection:
[mslug3s.zip](https://github.com/finalburnneo/FBNeo/files/8715344/mslug3s.zip)
-----------------
=> update ips function

src/burn/drv/galaxian/d_galaxian.cpp, src/burn/drv/pst90s/d_hyperpac.cpp
sync mame : https://github.com/mamedev/mame/commit/5803e4145cfbe269fdd71ce3c1f7660950b751c7
=> d_hyperpac.cpp : corrected title for honeydol

src/burn/drv/megadrive/d_megadrive.cpp
=> d_megadrive: smsbrawl

src/burn/drv/neogeo/neo_run.cpp
adjust sprite frame counter on line 0 instead of 248 (vblank start), fixes blazing star
=> neogeo: another bugfix for issue introduced in commit - f412f7b5387ae04fcda42a0b00321cb2c051ff0e

src/burn/drv/capcom/d_cps2.cpp
updated to latest version.
labels as requested by hack author
=> d_cps2: sfz3mix 0.13

src/burn/drv/pre90s/d_capbowl.cpp, src/burn/drv/sega/d_sys1.cpp
sync mame
clone sets as mame (for test):
[wbmlbg.zip](https://github.com/finalburnneo/FBNeo/files/8793528/wbmlbg.zip)
[wbmlbge.zip](https://github.com/finalburnneo/FBNeo/files/8793529/wbmlbge.zip)
[wbmld.zip](https://github.com/finalburnneo/FBNeo/files/8793530/wbmld.zip)
[wbmljod.zip](https://github.com/finalburnneo/FBNeo/files/8793531/wbmljod.zip)
[wbmlvcd.zip](https://github.com/finalburnneo/FBNeo/files/8793532/wbmlvcd.zip)
=> update d_sys1.cpp : Add clone sets of wbml

src/burn/bitswap.h, src/burn/drv/galaxian/d_galaxian.cpp, src/burn/drv/pre90s/d_vicdual.cpp
[1] add Startrks dip
[2] samurai -> samuraij
[3] add samurai
[4] samurai & samuraij BurnDriverD -> BurnDriver
[5] add nostromo
[6] startrks clone to nostromo
[7] nostromo & startrks useing Startrks dip
=> d_vicdual.cpp : sync with mame

src/burn/drv/neogeo/d_neogeo.cpp
=> d_neogeo: teot

src/burn/drv/neogeo/d_neogeo.cpp
Simplified operation of the third P-ROM
=> d_neogeo.cpp : test

src/burn/drv/nes/d_nes.cpp
Thanks for reading this, unsure which rev was the OG included in this, but this is the REV B either way.
With Header : 4E 45 53 1A 20 00 E3 10 00 00 00 00 00 00 00 00
=> Rev B of the ROM

src/burn/burn.h, src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/neogeo/neo_run.cpp, src/burner/qt/burner_qt.h, src/burner/qt/main.cpp, src/burner/sdl/ips_manager.cpp, src/burner/win32/ips_manager.cpp
[1] Add some ips macros
[2] Adjust ips logic for neogeo/cps-1
[3] Simplified loading and mapping of neogeo's Extra Rom
[4] Standardize naming of rom labels in some neogeo hack sets
[5] Enable extra rom in neogeo hack ips
[6] wofjdr update to 20220603
=> update ips function & others

src/burn/drv/neogeo/d_neogeo.cpp
[RomName.txt](https://github.com/finalburnneo/FBNeo/files/8872480/RomName.txt)
@dinkc64 Hi, dink
The document has been updated with details
=> d_neogeo.cpp : Add mslug series of hack games

src/burn/drv/nes/d_nes.cpp
Updated to v22 (latest version)
=> d_nes: drgarfield v22

src/burn/drv/nes/d_nes.cpp, src/burn/drv/pre90s/d_4enraya.cpp
[1] Add clone of unkpacg
[2] Add unksig and its clones
=> d_4enraya.cpp : Add clone of unkpacg

src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/pst90s/d_seta2.cpp
=> update some hack games

src/burner/sdl/sdl2_gui_ingame.cpp
=> SDL2: Fix typo that sends screenshot of ingame menu out of screen

src/burner/sdl/main.cpp, src/burner/sdl/sdl2_gui_ingame.cpp, src/intf/input/sdl/inp_sdl2.cpp
It is now possible to map joysticks buttons or remap game controllers buttons in ingame menu.
A file named gamecontrollerdb.txt is created in config folder (where fbneo.ini is) and loaded when fbneo starts.
It is possible to manually create or edit gamecontrollerdb.txt (for example, to change controller name).
=> SDL2: add a simple controller buttons mapping menu

src/burn/drv/capcom/d_cps2.cpp
=> d_cps2: spf2tcb v1.1

src/burn/drv/irem/d_m72.cpp, src/burn/drv/pre90s/d_mitchell.cpp
Super Marukin-Ban (Japan 911128) [system11, porchy]
=> d_mitchell.cpp : New working clones

src/burn/drv/neogeo/d_neogeo.cpp
=> d_neogeo: teot beta 6

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/neogeo/d_neogeo.cpp
Added Captain Commando Readjusted
=> d_cps1: captre v1.0

src/burn/drv/megadrive/d_megadrive.cpp
=> d_megadrive: ppersiar v1.3

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/megadrive/d_megadrive.cpp
updated to latest version.
Also, d_megadrive: jtoblivion genre fix.
=> d_cps1: dinore v1.2

src/burn/drv/nes/d_nes.cpp
=> d_nes: 8bitxmas21 label

src/burn/drv/pst90s/d_hyprduel.cpp
=> hiscore support for Hyper Duel

src/burn/devices/epic12.cpp
@dinkc64 cv1k runahead gets fairly playable on my computer with those changes (about 5 times faster), and i didn't notice any emulation issue, does it look safe to you ?
=> d_cv1k: first attempt at reducing runahead memory footprint

src/burn/drv/capcom/d_cps2.cpp
=> d_cps2: ssf2tnl 0.7.1

src/burn/drv/capcom/d_cps2.cpp
=> d_cps2: Inputlist for ffightaec2

src/burn/drv/pgm/d_pgm.cpp
Knights of Valour Plus - New Biography of Heroes (V120)
=> d_pgm: add kovplusq

src/burner/gamc.cpp, src/burner/gami.cpp, src/burner/sdl/burner_sdl.h, src/burner/sdl/config.cpp, src/burner/sdl/input_sdl2.cpp, src/burner/sdl/main.cpp, src/burner/sdl/sdl2_gui.cpp, src/burner/sdl/sdl2_gui_ingame.cpp, src/intf/input/sdl/inp_sdl2.cpp
We can now define input defaults for any player, any game, together with keyboard/joysticks mapping.
Macros are also supported.
Autofire supported and added a menu to set fire rate.
Also some code optimizations in startup and controllers config.
=> SDL2: Input mapping menu with macros and autofire

src/burn/drv/neogeo/d_neogeo.cpp
Metal Slug 5 (Extend Ver. 2022, Hack)
=> d_neogeo.cpp: add mslug5ex

src/burn/drv/pgm/d_pgm.cpp
add Xi You Shi E Zhuan Super Plus (Qun Mo Luan Wu New 211 Revision) (oldsplusnr211) update kovplus12dw to 20220727
=> d_pgm.cpp: update hack games

src/burn/drv/pst90s/d_tecmosys.cpp
=> pst90s: tecmosys input

src/burn/drv/neogeo/d_neogeo.cpp
Test: https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=sharing
=> d_neogeo.cpp: update hacks by author request (v2)

src/burn/drv/capcom/d_cps2.cpp, src/burn/drv/midway/d_tunit.cpp
=> d_tunit: nbajamre

src/burn/drv/neogeo/d_neogeo.cpp
Test: https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=sharing
=> d_neogeo.cpp: update hack games

src/burn/drv/neogeo/d_neogeo.cpp
Test: https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=sharing
=> d_neogeo: update hack games

src/burn/drv/cave/d_sailormn.cpp
Special thanks to barbudreadmon
=> d_sailormn: extended prog memory for ips

projectfiles/visualstudio-2015/fba_vs2010.vcxproj, projectfiles/visualstudio-2015/fba_vs2010.vcxproj.filters, projectfiles/visualstudio-2019/fba_vs2010.vcxproj, projectfiles/visualstudio-2019/fba_vs2010.vcxproj.filters, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj.filters, src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/pre90s/d_pkunwar.cpp
[1] update msvc project for d_exidy440
[2] d_pkunwar: fix a typo
=> update msvc project for d_exidy440

projectfiles/visualstudio-2015/fba_vs2010.vcxproj, projectfiles/visualstudio-2015/fba_vs2010.vcxproj.filters, projectfiles/visualstudio-2019/fba_vs2010.vcxproj, projectfiles/visualstudio-2019/fba_vs2010.vcxproj.filters, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj.filters, src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/pre90s/d_olibochu.cpp, src/burn/drv/pst90s/d_vamphalf.cpp
[1] d_cps1 & d_neogeo: update hack games
[2] d_olibochu & d_vamphalf sync mame
=> update msvc project for pic8259 & etc

src/burn/drv/konami/d_simpsons.cpp
The Simpsons (4 Players World, set 3) [Jorge Silva]
=> d_simpsons.cpp: sync mame

src/burn/drv/megadrive/d_megadrive.cpp
Added correct crc32, romname.
base: megamanrb rom + (U-RB)-v105 ips
I believe the original intention was add jp-rom and megamanrb with  "fixer upper" patch. if this isn't correct let me know.
=> d_megadrive: md_megamanfix

projectfiles/visualstudio-2015/fba_vs2010.vcxproj, projectfiles/visualstudio-2015/fba_vs2010.vcxproj.filters, projectfiles/visualstudio-2019/fba_vs2010.vcxproj, projectfiles/visualstudio-2019/fba_vs2010.vcxproj.filters, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj.filters, src/burn/drv/dataeast/d_compgolf.cpp
=> update msvc project for d_compgolf

src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/pst90s/d_crospang.cpp
=> d_neogeo: update mslugxsc & mslug5sg

src/burn/drv/pst90s/d_cischeat.cpp
d_cischeat: Scud Hammer (ver 1.4) [SpinalFeyd]
=> d_cischeat: New working clones

src/burn/drv/pre90s/d_lwings.cpp, src/burn/drv/pre90s/d_mastboyo.cpp
d_lwings: Trojan (location test) [coolmod, rtw, Brian Troha, Sean Sutton, Smitdogg, The Dumping Union]
d_mastboyo: Trojan (location test)
=> New working clones

projectfiles/visualstudio-2015/fba_vs2010.vcxproj, projectfiles/visualstudio-2015/fba_vs2010.vcxproj.filters, projectfiles/visualstudio-2019/fba_vs2010.vcxproj, projectfiles/visualstudio-2019/fba_vs2010.vcxproj.filters, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj.filters, src/burn/drv/cave/d_cv1k.cpp, src/burn/drv/pre90s/d_williams.cpp
[1] update msvc project for dtimer
[2] d_williams: dumped PROMs for defenderj [Guru]; add Defense (Defender bootleg)
[3] d_cv1k: Fix FullName of ddpsdoj & sdojak (怒首領蜂 最大往生)
=> update msvc project for dtimer & etc

src/burn/drv/midway/d_tunit.cpp, src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/pre90s/d_jrpacman.cpp, src/burn/drv/pst90s/d_itech32.cpp, src/burn/drv/pst90s/d_shangha3.cpp
d_itech32: bloodstm221
d_shangha3: shangha3u
d_tunit: mk2chal
d_jrpacman: jrpacman; jrpacmanf
=> ROM labels updates [Brian Troha]

src/burn/drv/nes/d_nes.cpp
=> d_nes: skartfighter

src/burn/drv/cave/d_cv1k.cpp
add Ibara (2005/03/22 MASTER VER.., '06. 3. 7 ver.) 
ibara to ibarao
=> d_cv1k: sync mame

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/taito/d_asuka.cpp
Bonze Adventure (World, prototype, older) [BL]
=> d_asuka: New working clones

src/burn/devices/atarimo.h, src/burn/devices/epic12.cpp, src/burn/devices/poly.h, src/burn/devices/rectangle.h, src/burn/drv/pst90s/d_seta2.cpp, src/burn/drv/pst90s/d_ssv.cpp, src/burn/drv/taito/d_galastrm.cpp
In the same way as the dtimer problem on some compilers, it might be related to https://github.com/finalburnneo/FBNeo/issues/1129
=> normalize rectangle object

src/dep/kaillera/client/net.cpp
=> net.cpp: use BUILD_X64_EXE

src/burn/drv/pgm/d_pgm.cpp, src/burn/drv/pre90s/d_gunsmoke.cpp, src/burn/drv/pre90s/d_mrjong.cpp
d_gunsmoke: add Gun.Smoke (USA and Canada, 1986/01/20) [Victor Fernandez (City Game), Jordi Beltrán]
d_gunsmoke: make game string build date more readable
d_mrjong: fixed horizontal sprite offset when screen is flipped [pcornier]
d_pgm: update kovplus12dw to 2022/12/17
=> update d_gunsmoke, d_mrjong, d_pgm

src/burn/drv/cave/d_cv1k.cpp, src/burn/drv/pre90s/d_gaplus.cpp, src/burn/drv/pre90s/d_solomon.cpp
d_cv1k: Espgaluda II (2005/11/14.MASTER VER.) [twistedsymphony]
d_gaplus: Gaplus (GP7) [Arcadecomponents.com, Brian Troha]
d_solomon: add Solomon no Kagi (T-Chi)
=> update: d_cv1k / d_gaplus / d_solomon

src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/pgm/d_pgm.cpp, src/burn/drv/sega/d_bankp.cpp, src/burn/drv/taito/d_taitosj.cpp
d_bankp: Bank Panic (Tecfri bootleg) [Eduardo Anay, Recreativas.org][clawgrip]
d_taitosj: Jungle King (Japan, earlier, alt) [CWorks][DavidHaywood]
d_neogeo: mslugxsc to 20221231
d_pgm: kovplus12dw to 20221225
=> update: d_bankp / d_taitosj / d_neogeo / d_pgm

src/burn/drv/capcom/cps.h, src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/pre90s/d_ddragon.cpp
d_ddragon: Added Double Dragon II layer priority PROM to clones [jotego]
d_cps1: Added SFZ63B mapper [TwistedTom]
d_cps1: Added proper B board GAL fusemap to run ffightae hack on hardware [cuavas]
d_cps1: add 3 tchi hacks & dinosyn to 20221221
=> update d_ddragon & d_cps1

src/burn/drv/spectrum/d_spectrum.cpp
trashmanes - removed extra dot in filename.
=> d_spectrum: typo

src/burn/drv/spectrum/d_spectrum.cpp
=> fix file-size

src/burn/drv/pgm/d_pgm.cpp, src/burn/drv/pgm/pgm.h, src/burn/drv/pgm/pgm_draw.cpp, src/burn/drv/pgm/pgm_run.cpp
=> pgm: Fix kovqxzbws

src/burn/drv/megadrive/d_megadrive.cpp
Tournament Edition. Rebalanced and updated version by original author [Oruam] 'md_fightveng' marked as clone.
=> d_megadrive: add fightvengt

src/burn/burn.h, src/burn/drv/pgm/d_pgm.cpp, src/burn/drv/pgm/pgm_draw.cpp, src/burn/drv/pgm/pgm_run.cpp, src/burner/win32/ips_manager.cpp
test:
kovqxzbws [kovshp.zip](https://github.com/finalburnneo/FBNeo/files/10475206/kovshp.zip)
kov2dzxx [kov2.zip](https://github.com/finalburnneo/FBNeo/files/10475207/kov2.zip)
=> ips: pgm more features support

src/burn/drv/megadrive/d_megadrive.cpp
Added SoR - Killer Difficulty (version as on ips file)
=> md_megadrive: sorkiller

src/burn/drv/pre90s/d_omegrace.cpp
=> d_omegrace: Omega Race (set 3, 7/27) [mdeslaur]

src/burn/drv/nes/d_nes.cpp
[1] add T-Chi games
[2] add 2 parent games
[3] fix some info
=> d_nes: add T-Chi games

src/burn/drv/nes/d_nes.cpp
test: https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=share_link
=> d_nes: add RoboCop (T-Chi)

src/burn/drv/dataeast/d_decocass.cpp, src/burn/drv/pre90s/d_gunsmoke.cpp
d_gunsmoke: Fixed typo in gunsmokeuc.
d_decocass: Added new tape image for cnebula [David Haywood]
=> Some changes in Pre90s and Dataeast

src/burn/burn.h, src/burner/win32/ips_manager.cpp
Increase the temporary memory for loading the rom
=> ips: add IPS_LOAD_OFFSET

src/burn/drv/capcom/d_cps1.cpp
=> d_cps1: sf2mix 1.3

src/burn/drv/nes/d_nes.cpp
Jackal - Endless Mission (v1.2)
Contra - Demon Contra
Contra - The Last Rebirth
=> d_nes: add Information

src/burn/drv/taito/d_taitoh.cpp
removed extra "BDF_HISCORE_SUPPORTED"
=> d_taitoh, fixed typo

src/burn/drv/pst90s/d_pushman.cpp
add Pushman (Top Tronic license)
=> d_pushman: rom labels for pushman [f205v]

src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/sega/d_segac2.cpp
mslug3lw to 20230215
mslug5es to 20230208
test: https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=share_link
=> d_neogeo: author requested

src/burn/drv/pgm/d_pgm.cpp
Thanks to khanhnguyen1988
test: https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=share_link
=> d_pgm: Yi Tong Zhong Yuan - Warriors

src/burn/drv/pgm/d_pgm.cpp
=> d_pgm: kovytzyws hack spr

src/burn/burn.h, src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/cave/d_sailormn.cpp, src/burn/drv/megadrive/megadrive.cpp, src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/neogeo/neo_run.cpp, src/burn/drv/neogeo/neogeo.cpp, src/burn/drv/pgm/pgm_run.cpp, src/burn/load.cpp, src/burner/qt/burner_qt.h, src/burner/qt/main.cpp, src/burner/sdl/ips_manager.cpp, src/burner/win32/burner_win32.h, src/burner/win32/ips_manager.cpp, src/burner/win32/main.cpp, src/burner/win32/sel.cpp
- Reduce the number of repeated calls
- More precise control of memory usage
- Explicit ips entry point
[ips_test.zip](https://github.com/finalburnneo/FBNeo/files/10825830/ips_test.zip)
=> Rewrite ips code

src/burn/drv/neogeo/d_neogeo.cpp
=> d_neogeo : Fix KOF2001 bootleg AES mode

src/burn/drv/neogeo/d_neogeo.cpp
=> d_neogeo : update mslug hacks

src/burn/drv/nes/d_nes.cpp
=> d_nes: nemulesis

src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/pgm/d_pgm.cpp, src/burn/drv/pgm/pgm_run.cpp
d_pgm : add kovpluststd & kovplushsqj
=> pgm_run : fix Illegal instructions [dink]

src/burn/drv/neogeo/d_neogeo.cpp
2023-03-04
bug fixes in collision boxes (all characters)
yellow/orange energy bar
2nd palette for mizuki and kuroko.
=> d_neogeo: samsho2pe

src/burn/drv/pre90s/d_thepit.cpp
The Pit (Centuri Inc) [Domenico Cervini]
=> d_thepit : New working clones

src/burn/drv/capcom/d_cps1.cpp
=> d_cps1 : update hack games

src/burn/drv/pgm/d_pgm.cpp
- fix https://github.com/finalburnneo/FBNeo/issues/1173
test : https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=sharing
=> d_pgm : fix kovlsyx & upd kovplus20tx

src/burn/drv/neogeo/d_neogeo.cpp
=> d_neogeo : update mslug3lw & mslug5sg

src/burn/drv/capcom/d_cps1.cpp
updated to laterst version
dinore 1.3
captre 1.1
=> d_cps1: captre, dinore

src/burn/drv/neogeo/d_neogeo.cpp
=> d_neogeo : update mslugxcq & mslug3cq

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/capcom/d_cps2.cpp, src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/neogeo/neo_run.cpp
- Don't treat puzzldpr as a clone [Haze]
=> neogeo : add irrmaze BIOS [Simon Taylor]

src/burn/drv/irem/d_m92.cpp
- d_m92 : Added IC locations and PLDs to most sets, minor ROM label corrections. [The PLD Archive, Porchy, Brian Troha, The Dumping Union]
- d_m92 : Added some Japanese names
=> d_m92 : some fixes [Brian Troha]

src/burn/drv/neogeo/d_neogeo.cpp
2023-Mar-13: charlotte power bar points don't reset in defense.
=> d_neogeo: samsho2pe bugfix

src/burn/drv/capcom/d_cps1.cpp
Updated to latest version.
Minor bug fix.
=> d_cps1: dinore 1.3.1

src/burn/drv/capcom/d_cps2.cpp, src/burn/drv/neogeo/d_neogeo.cpp
- d_neogeo : Metal Slug 5 (Boss Battles, Hack)
- d_cps2 : Street Fighter Alpha 2 Ultra
- 
=> d_cps2 & d_neogeo : add hack games

src/burn/drv/capcom/d_cps2.cpp, src/burn/drv/neogeo/d_neogeo.cpp
- d_cps2 : Author request to add beta tag (sfa2ultra)
- d_neogeo : update mslug3 hacks
=> update d_cps2 & d_neogeo

src/burn/drv/megadrive/d_megadrive.cpp, src/burn/drv/neogeo/d_neogeo.cpp
=> d_megadrive & d_neogeo : update hack games

src/burn/drv/pre90s/d_invaders.cpp
added hiscore support - re-worked DrvFrame to ensure hiscores work correctly.
=> added hiscore support to invaders

src/burn/drv/neogeo/d_neogeo.cpp
- ips : handle expanded data connections after sma decryption
kof99ae ips - [kof99.zip](https://github.com/finalburnneo/FBNeo/files/11069057/kof99.zip)
mslug3cq test : https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=share_link
=> d_neogeo : update mslug3cq & etc.

src/burn/drv/pre90s/d_alinvade.cpp, src/burn/drv/pre90s/d_alpha68k.cpp, src/burn/drv/pre90s/d_battlane.cpp, src/burn/drv/pre90s/d_battlex.cpp, src/burn/drv/pre90s/d_blockade.cpp, src/burn/drv/pre90s/d_blockout.cpp, src/burn/drv/pre90s/d_bogeyman.cpp, src/burn/drv/pre90s/d_bzone.cpp, src/burn/drv/pre90s/d_calorie.cpp, src/burn/drv/pre90s/d_canyon.cpp, src/burn/drv/pre90s/d_ccastles.cpp, src/burn/drv/pre90s/d_cheekyms.cpp, src/burn/drv/pre90s/d_cloak.cpp, src/burn/drv/pre90s/d_cop01.cpp, src/burn/drv/pre90s/d_dacholer.cpp, src/burn/drv/pre90s/d_dday.cpp, src/burn/drv/pre90s/d_deadang.cpp, src/burn/drv/pre90s/d_djboy.cpp, src/burn/drv/pre90s/d_dogfgt.cpp, src/burn/drv/pre90s/d_dorachan.cpp, src/burn/drv/pre90s/d_drmicro.cpp, src/burn/drv/pre90s/d_dynduke.cpp, src/burn/drv/pre90s/d_efdt.cpp, src/burn/drv/pre90s/d_exprraid.cpp, src/burn/drv/pre90s/d_invaders.cpp
hiscore support added to multiple games (other issues with games such as sound have not been updated)
=> hiscore support added for alinvade, sstingry, kyros, kyrosj, battlane, battlane2, battlane3, battlex, dodgeman

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj
* Add missing source code files.
* Move -Wno-documentation to CLANG_WARN_DOCUMENTATION_COMMENTS.
* Enable format warnings.
=> Update Xcode project

src/burn/drv/nes/d_nes.cpp, src/burn/drv/sega/d_segac2.cpp
d_nes : add Rockman 3 - Dr. Wily no Saigo! (T-Chi) 20230315 [NOKOH]
d_segac2 : Waku Waku Anpanman (Rev A) [Darksoft, TeamEurope]
nes test : https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=share_link
=> update d_nes & d_segac2

src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/nes/d_nes.cpp
=> d_neogeo : update hack games

src/burn/drv/nes/d_nes.cpp
=> d_nes : fix deletion caused by unsynchronized

src/burn/drv/sms/d_sms.cpp
=> d_sms: evil v1.0.6

src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/pre90s/d_pacman.cpp
2023-04-16
- Charlotte state defense
- Kyoshiro state defense
Also, **d_pacman: chuckieegg** - romName should be in lowercase + clone tag.
=> d_neogeo: samsho2pe bugfixes

src/burn/drv/megadrive/d_megadrive.cpp, src/burn/drv/nes/d_nes.cpp
'nes_kinni' is clone of 'nes_muscle'
Also, 'md_umk3osc' typo fix
=> d_nes: kinni

src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/pgm/d_pgm.cpp, src/burn/drv/pre90s/d_ddragon.cpp
d_ddragon : d_ddragon : add Dangerous Dungeons (set 2)
d_pgm : update oldsplusnr
d_neogeo : mslug hacks
=> update : d_ddragon / d_pgm / d_neogeo

src/burn/drv/spectrum/d_spectrum.cpp
Updated to latest version
2023-may-11: fix bug with IA level.
=> d_spectrum: speccysoccer

src/burn/drv/megadrive/d_megadrive.cpp, src/burn/drv/neogeo/d_neogeo.cpp
Updated to latest version (1.1).
Also, d_neogeo: samsho2pe v. 1.2
2023-05-30:
- Rebalanced damage jump kick light, medium and strong, all characters
- Readjusted dizzy all chars
=> d_megadrive: megamanswred

src/burn/drv/coleco/d_coleco.cpp, src/burn/drv/sg1000/d_sg1000.cpp, src/burn/drv/sms/d_sms.cpp
All updated to latest version.
=> Vexed 1.08: coleco, gamegear, sg1k, sms

src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/neogeo/neo_run.cpp, src/burn/drv/neogeo/neogeo.h
Merge some hacks
Sort by series
Update hacks to the latest
test : https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=sharing
=> neogeo : update hack games

src/burn/drv/neogeo/d_neogeo.cpp
Test : https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=sharing
=> d_neogeo : to LF / typo / add mslug5sv

src/burn/burn.cpp, src/burn/burn.h, src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/neogeo/neo_run.cpp, src/burner/sdl/localise_gamelist.cpp, src/burner/win32/localise_gamelist.cpp
- d_neogeo : hack games update to latest
- add ShortNameA for all subgames
- add subgame gamelistex language glt support (requires loading basic gamelist)
test :
https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=sharing
gamelistex test:
[gamelist.zip](https://github.com/finalburnneo/FBNeo/files/11802372/gamelist.zip)
=> win32 : separate names for subgames

src/burn/drv/neogeo/d_neogeo.cpp
Fix header files that should not be included
=> d_neogeo : fix header files

src/burner/burner.h, src/burner/cong.cpp, src/burner/gami.cpp, src/burner/win32/main.cpp
fbneo kof99t 0
fbneo kof99t 1
fbneo kof99t 2
...
=> win32 : subgames add command line launch

src/burn/drv/dataeast/d_dec8.cpp, src/burn/drv/pst90s/d_pipedrm.cpp
Hatris (show version) [twistedsymphony]
=> d_pipedrm : add hatrisp

src/burn/drv/pre90s/d_armedf.cpp
Terra Force (US, alternate sound) [caius]
=> d_armedf : New working clones

src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/pre90s/d_armedf.cpp, src/burn/drv/pst90s/d_pipedrm.cpp
- hatrisp: correct size/crc
- terrafua: correct sizes
- samsho2pe: updated to version (23-07-10)
=> pre90s, pst90s fixes. samsho2pe update

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/neogeo/d_neogeo.cpp
d_cps1: merge some hack games
d_cps1: sync FullName
d_cps1: Nemo (Japan 901120, 89625B-1 ROM board) [Corrado Tomaselli, Brian Troha]
d_neogeo: update kof2k1ult (kof2k1bs) to 20230606
d_neogeo: update mslug1v2 (mslugaks) to 20230626
d_neogeo: update mslugxdg (mslugxaks) to 20230626
d_neogeo: update mslug5bs (mslug5aks) to 20230626
=> d_cps1 & d_neogeo: update hack games

src/burn/drv/sms/d_sms.cpp
=> d_sms: ggaleste3

src/burn/drv/megadrive/megadrive.cpp
attempt at backporting https://github.com/notaz/picodrive/commit/35f2b65ef708e7afc922ceda8d00b716de289610
@dinkc64 does it look ok to you ?
=> megadrive: implement overclocking

src/burn/drv/spectrum/d_spectrum.cpp
Updated to latest version.
v1.1: corrected ghost bullets.
=> d_spectrum: borielrun v1.1

src/burn/burn.cpp, src/burn/burn.h, src/burn/drv/neogeo/d_neogeo.cpp
d_neogeo: update hack games
burn: fix a few bugs
=> d_neogeo: update hack games / burn: fix a few bugs

src/burn/drv/pst90s/d_seta2.cpp
=> d_seta2: update hack games

src/burn/drv/sega/d_sys1.cpp
Flicky (64k Version, on Up'n Down boardset, set 2) [caius]
=> d_sys1: New working clones

src/burn/drv/spectrum/d_spectrum.cpp
2023-09-25: Smoke effect added
=> d_spectrum: bombsweep

src/burn/drv/neogeo/d_neogeo.cpp
2023-10-05:
Fixed hit-counter (it's ok!)
Kuroko's lines as a judge have been adjusted, the lyrics no longer disappear Mizuki and Kuroko Story Mode and Final, the 3 cutting scenes were introduced kuroko and Mizuki conversation, Scene 1 talking to Mizuki in the middle of the rocks, scene 2 talking to kuroko, scene 3 in the middle of the rocks for battle against Mizuki! Ukyo Update collor 8, palette similar to samsho3
Charlotte Update collor 6, darkened armor and hair Nicotine update collor 6, Lilac Hat!
Kuroko update collor 2,3,4,5,6,7,8, darkened clothes Genan update collor 6, new collor!
Kuroko light punch down adjusted image, increased range hitbox attack
=> d_neogeo: samsho2pe v. 1.4

src/burn/drv/nes/d_nes.cpp, src/burn/drv/pst90s/d_seta2.cpp, src/burner/win32/ips_manager.cpp
d_seta2: update grdianshs
d_nes: update nes_castlevanialt to 4.0
ips_manager: Allow customized extension values
=> d_seta2 & d_nes: update hack games, & etc

src/burn/drv/capcom/d_cps1.cpp, src/burner/win32/ips_manager.cpp
d_cps1: update hack games
ips_manager: reordering of logic
=> d_cps1: update hack games & etc

src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/pst90s/d_seta2.cpp
=> d_neogeo.cpp & d_seta2.cpp: update hack games

src/burn/drv/capcom/d_cps1.cpp
Updated... Again to latest version.
=> d_cps1: captre v1.2

projectfiles/visualstudio-2015/fba_vs2010.vcxproj, projectfiles/visualstudio-2015/fba_vs2010.vcxproj.filters, projectfiles/visualstudio-2019/fba_vs2010.vcxproj, projectfiles/visualstudio-2019/fba_vs2010.vcxproj.filters, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj.filters, src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/neogeo/d_neogeo.cpp, src/burn/stdfunc.h, src/burner/win32/romdata.cpp
update msvc project
romdata.cpp: Accurately differentiate between ASCII/UTF8/UTF8BOM in UTF8 & to LF. stdfunc.h: fix for STD_ROM_PICK macro not booting from romdata. d_cps1: GameConfig is correctly indexed when entering the game from romdata. d_neogeo.cpp: update hack games.
=> update msvc project & romdata & hack games

src/burn/drv/capcom/d_cps2.cpp
=> d_cps2: sfz3te v1.2

src/burn/drv/capcom/cps.h, src/burn/drv/capcom/cps_config.cpp, src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/cave/d_sailormn.cpp, src/burn/drv/pgm/d_pgm.cpp, src/burn/drv/pgm/pgm.h, src/burn/drv/pgm/pgm_run.cpp, src/burn/drv/pst90s/d_seta2.cpp
d_pgm: kovp12em
pgm: add MapperHack
d_sailormn: sailmnhy/sailmnxy/sailmnee/sailmnyh/sailmnyy/sailmnkf/sailmnsl & Oc to 150% & Region Dip
d_seta2: grdiands/grdiansy
teast: https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=drive_link
=> update hack game

src/burn/drv/capcom/d_cps1.cpp
=> d_cps1: update hack game & fix dip

src/burn/drv/capcom/d_cps1.cpp
Added version 1.3 as requested by Author.
---
Street Fighter II Hyper Fighting with Champion Edition speed and new palletes.
=> d_cps1: sf2hfsce

projectfiles/visualstudio-2015/fba_vs2010.vcxproj, projectfiles/visualstudio-2015/fba_vs2010.vcxproj.filters, projectfiles/visualstudio-2019/fba_vs2010.vcxproj, projectfiles/visualstudio-2019/fba_vs2010.vcxproj.filters, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj, projectfiles/visualstudio-2022/fbneo_vs2022.vcxproj.filters
=> update vc project for d_itech8

src/burn/drv/atari/d_skullxbo.cpp, src/burn/drv/pst90s/d_cischeat.cpp, src/burn/drv/pst90s/d_itech32.cpp
sftm should be GBF_VSFIGHT
skullxbo should be GBF_SCRFIGHT
wildplt should be GBF_SHOOT
=> Some Genre fixes [Goratrix]

src/burn/drv/neogeo/d_neogeo.cpp
- fix clones : timesupd/ffury2es
- update kof99sk
test : https://drive.google.com/drive/folders/1qqk2cNlE5ecb6wMGjJmAqTef2xVgshyJ?usp=drive_link
=> d_neogeo : fix clones [dangonzilla]

src/burn/drv/neogeo/d_neogeo.cpp, src/burn/drv/neogeo/neo_run.cpp, src/burn/drv/neogeo/neogeo.h
d_neogeo: gowcaiet/mslug5bs/mslug5cq/mslug5sg, mslug5 can handle prg's greater than 0x800000.
neo_run.cpp/neogeo.h: The prg length needs to be publicized, and nAllCodeSize is set as a global variable.
=> d_neogeo: update hack game & etc

src/burn/drv/neogeo/d_neogeo.cpp
update: mslug5bs/mslug5cq/mslug5sg
ips: 
https://github.com/taoenwen/FBNeo_IPS/commit/2f1a441cee8acabdfd7d91caefa23b045cc90739
https://github.com/taoenwen/FBNeo_IPS/commit/be3d5465f11eb7fec427f593d1b23659ff0dd3c2
https://github.com/taoenwen/FBNeo_IPS/commit/9c62e854dd97d50dc5e445273ecca80ebe5df702
=> d_neogeo: update mslug5 hack games

src/burn/drv/neogeo/d_neogeo.cpp
ips: https://github.com/taoenwen/FBNeo_IPS/commit/3035f832e94466b2383bde1a81cd8e63be31ff63
=> d_neogeo: add Cyborg Force (Homebrew)

src/burn/drv/capcom/d_cps2.cpp
Updated to latest version (v0.9b)
=> d_cps2: ssf2tnl

src/burn/drv/megadrive/d_megadrive.cpp
=> d_megadrive: astebros

src/burn/drv/sg1000/d_sg1000.cpp
fixed fileName
this Solves the issue #1776
=> d_sg1000: guntus

src/burn/drv/capcom/d_cps2.cpp
=> d_cps2: sfz3mix

src/burn/drv/neogeo/d_neogeo.cpp
=> d_neogeo: kof94te

src/burn/drv/nes/d_nes.cpp
transformers: Fixed bug when you try generate N3S datFile.
shancara: Changed CRC, now is 7ea7e5df. current CRC doesn't match any file (original rom from fbneo list, crc mentioned on romhacking).
Source rom: 'shancaraj' (crc: dcfe4112), from fbneo list.
[ips_patchs.zip](https://github.com/user-attachments/files/15855957/ips_patchs.zip)
=> d_nes: some changes

src/burn/drv/capcom/d_cps2.cpp
=> d_cps2: sfa2ultra

src/burn/drv/neogeo/d_neogeo.cpp
=> d_neogeo: karnovre

src/burn/drv/megadrive/d_megadrive.cpp
=> d_megadrive: umk3osc

src/burn/drv/neogeo/d_neogeo.cpp
Updated to latest version (2024-05-23)
=> d_neogeo: gowcaiet

src/burn/drv/megadrive/d_megadrive.cpp
updated to 1.0a (Solved hidden palace bug? *).
*Tails (and sometimes Sonic) get stucked in hidden palace because knuckles jumps out screen instead hit eggman's ship. So game cutscene don't advance...
=> d_megadrive: s3compes

src/burn/drv/nes/d_nes.cpp
hoops, USA (parent)
moerojrbas, Japan (clone)
=> d_nes: add some games

src/burn/drv/megadrive/d_megadrive.cpp, src/burn/drv/sms/d_sms.cpp
=> d_sms: frontierforce

src/burn/drv/nes/d_nes.cpp
=> d_nes: marioadventure3

src/burn/drv/nes/d_nes.cpp
=> 1.01 version

src/burn/drv/megadrive/d_megadrive.cpp
order do apply patch (in ssf2u original rom).
1. SSF2_GlamorQueen.ips
2. SSF2_GlamorQueen_NoPause.ips
=> d_megadrive: bssf2gq crc fix.

src/burn/drv/snes/d_snes.cpp
=> d_snes: ff6sc

src/burn/drv/pre90s/d_dkong.cpp
You guys forgot to add the proper size which is twice that you put in :)
=> dkong, add dkspkyte (correct size)

src/burn/drv/spectrum/d_spectrum.cpp
=> Alien Astro Frenzy (new publisher)

src/burn/drv/megadrive/d_megadrive.cpp
=> FFight MD Update

src/burn/drv/taito/d_taitof3.cpp, src/burn/drv/taito/taitof3_snd.cpp
@dinkc64 what do you think of those changes ?
=> taitof3 updates

src/burn/drv/spectrum/d_spectrum.cpp
The first commit was the TZX, using TAP as set in code.
=> Jurl to 1.0

projectfiles/xcode/Emulator.xcodeproj/project.pbxproj, src/burner/macos/burner_macos.h, src/dep/libs/zlib/gzguts.h
=> fix: macOS build and Xcode files

src/burn/drv/sms/d_sms.cpp
=> new version (sms)

src/burn/drv/capcom/d_cps2.cpp
unsure about size attached picture for sizes.
=> sf2prime updated CRC

src/burn/drv/spectrum/d_spectrum.cpp
=> Update Poppy (ZX)

src/burn/drv/snes/d_snes.cpp
d_snes.cpp: add support to "Bordeline (HB)"
d_snes.cpp: rename SA-1 and FastROM speed hacks for consistency
d_snes.cpp: added some hacks reference URLs
=> d_snes.cpp: SNES update

src/burn/drv/snes/d_snes.cpp
- Marvel Super Heroes vs. Street Fighter (USA)
- Street Fighter EX Plus Alpha (USA)
- X-Men vs. Street Fighter (USA)
=> d_snes.cpp: added support to several unlicensed games

src/burn/drv/snes/d_snes.cpp
- Dragon Ball Z - Final Bout (USA) (Unl)
- King of Fighters 2000, The (USA) (Unl)
- King of Fighters '98, The (USA) (Unl)
- Men in Black (USA) (Unl)
- Mortal Kombat Mythologies - Gold 2000 (USA) (Unl)
- Soul Edge vs Samurai (USA) (Unl)
- Soul Blade (USA) (Unl)
- Tekken 2 (USA) (Unl)
=> d_snes.cpp: added the support for some unlicensed games

src/burn/drv/snes/d_snes.cpp
d_snes.cpp: "Bananas de Pijamas (USA) (Unl)" is clone of "Chester Cheetah - Too Cool to Fool (USA)"
=> d_snes.cpp: renamed some games to add their revision number

src/burn/drv/megadrive/d_megadrive.cpp
Trying do a pullrequest...
Updated the follow roms: bssf2gq (v2.7 + new url), peacocking2 (v2.42)
=> d_megadrive.cpp: updates

src/burn/drv/snes/d_snes.cpp
- Barbie - Super Model (USA)
- Barbie - Vacation Adventure (USA, Prototype)
- Hilda (HB)
- Incognity: A rover story (HB)
- Super Chase H.Q. (Australia)
=> d_snes.cpp: Added the support to 5 new SNES/Super Famicom games

src/burn/drv/snes/d_snes.cpp
- Bounty Sword (Japan)
- Emerald Dragon (Hack, English v1.2)
- Emerald Dragon (Hack, Spanish v1.1)
- Emerald Dragon (Japan)
- Pierre le Chef is... Out to Lunch (Euro)
- Super Big 2 (China) (Unl)
- Wayne's World (USA)
- Wayne's World (Euro)
=> d_snes.cpp: added the support to 8 new SNES/Super Famicom games

src/burn/drv/nes/d_nes.cpp, src/burn/drv/snes/d_snes.cpp
=> d_snes.cpp, d_nes.cpp: renaming of several misnamed roms

src/burn/drv/snes/d_snes.cpp
- Aguri Suzuki F-1 Super Driving (Euro)
- Aguri Suzuki F-1 Super Driving (Japan)
- Alien vs. Predator (Euro)
- Indiana Jones' Greatest Adventures (Euro)
- Indiana Jones' Greatest Adventures (Japan)
- K-fet Invaders (HB)
- Legend (Euro)
- Redline F-1 Racer (USA)
- Space Invaders - The Original Game (Australia)
- Super Goal! 2 (USA)
=> d_snes.cpp: added the support to 10 SNES games

src/burn/drv/snes/d_snes.cpp
- Faceball 2000 (USA)
- Jack Nicklaus Golf (USA)
- Mario's Early Years - Fun with Letters (USA)
- Mario's Early Years - Fun with Numbers (USA)
- Mario's Early Years - Preschool Fun (USA)
- Mario's Time Machine (USA)
- Street Sports - Street Hockey '95 (USA)
- Street Sports - Jammit (USA)
- True Golf Classics - Pebble Beach Golf Links (USA)
- True Golf Classics - Waialae Country Club (USA)
=> d_snes.cpp: added the support to 10 new SNES/Super Famicom games

src/burn/drv/capcom/d_cps1.cpp, src/burn/drv/snes/d_snes.cpp
d_cps1.cpp - dinosyn typo (cdj_syn.10f)
d_snes.cpp - add fireemblem776ti
=> adj. in d_cps1.cpp, d_snes.cpp

src/burn/drv/spectrum/d_spectrum.cpp
from author:
6-jun-25: Final version published
Added 5 extra levels in order to explain the final
=> d_spectrum.cpp - pyramid update

src/burn/drv/capcom/d_cps2.cpp
=> d_cps2.cpp - sf2prime update

src/burn/drv/megadrive/d_megadrive.cpp
quickNdirty dump with corrected crc
=> d_megadrive: add inkventure

src/burn/drv/megadrive/d_megadrive.cpp
v30a -> v31
[v30a_to_v31_patch.zip](https://github.com/user-attachments/files/20868282/v30a_to_v31_patch.zip)
=> d_megadrive.cpp - adj. in umk3osc

src/burn/drv/megadrive/d_megadrive.cpp
=> d_megadrive.cpp - umk3osc typo

src/burn/drv/nes/d_nes.cpp
Add Operation: Jump Out, english translation of Tobidase Daisakusen
=> adj. in d_nes.cpp - FDS: add oprjumpout

src/burn/drv/capcom/d_cps2.cpp, src/burn/drv/snes/d_snes.cpp
Add english translation for fire emblem 4.
adj in fireemblem4j, fireemblem4tsc, fireemblem4ttc (clone of fireemblem4te)
=> d_snes.cpp - add fireemblem4te

src/burn/drv/snes/d_snes.cpp
Add japanese ROM and english translation for "Ultima Kyouryuu Teikoku - The Savage Empire"
=> d_snes.cpp - add ultimasavempte and ultimasavempj

src/burn/drv/megadrive/d_megadrive.cpp
=> d_megadrive.cpp - adj in ffightmd

src/burn/drv/megadrive/d_megadrive.cpp, src/burn/drv/sms/d_sms.cpp
d_sms
add kenseidpt, mastdarkpt, zillionpt, zillion2pt
d_megadrive
add atomrobopt, atomrunpt, insectxpt
fixed fileName in insectxs and magichatpt
=> t-bra: add some translations in md/sms

src/burn/drv/snes/d_snes.cpp
t-bra
snes_3ninjaskbtp, snes_evotp, snes_inspgadgettp, snes_snoopyconcerttp, snes_tenchimuyoutp, snes_slrmoonanstorytp
classic games
snes_tenchimuyouj, snes_rtypeiiie (x)
(x) requested at neo-source
=> d_snes: add 6 t-bra translations + 2 games

src/burn/drv/megadrive/d_megadrive.cpp
Rick Dangerous DX & complete Infos for Earthion
=> d_megadrive.cpp: update

src/burn/drv/nes/d_nes.cpp, src/burn/drv/sms/d_sms.cpp
grrdeargospt, doubldraiipt, doubldraiiipt, doubledragonpt, dragninjapt, faxanadupt, termi2pt, sprgsolbrainpt
=> d_nes: t-bra - Add some translations

src/burn/drv/megadrive/d_megadrive.cpp
removed invalid char ("?") in fileName.
=> d_megadrive: typo in shrek, shrek2

src/burn/drv/megadrive/d_megadrive.cpp
=> Genesis rom update

src/burn/drv/megadrive/d_megadrive.cpp, src/burn/drv/neogeo/d_neogeo.cpp
ffightmd - 088 -> 089
doubled1 - beta 3 -> beta 3.2
=> adj in d_megadrive.cpp, d_neogeo.cpp

src/burn/drv/megadrive/d_megadrive.cpp, src/burn/drv/sms/d_sms.cpp, src/burn/drv/snes/d_snes.cpp
MD:
- Added "Paprium (Unlocked)": hack with all characters, routes and difficulty levels unlocked.
SMS:
- Added "Pyramid Escape"
- Updated "Mai Nurse"
SNES:
- Added "Mai Nurse"
- Fixed Screen Ratio "Tecmo Super NBA Basketball"
- Relocated "Marvel Super Heroes - War of the Gems Redux"
=> d_megadrive.cpp, d_sms.cpp, d_snes.cpp: MD, SMS and SNES update

src/burn/drv/sega/d_segas32.cpp
Have not tested this. I think it should be correct though. Please test before committing.
=> Fix text resolution hack flip

src/burn/drv/sega/d_segas32.cpp
You can also just use cliprect + 1 here, but I figured since tempclip is already incremented might as well use it
=> Multi flip width fix

src/burn/drv/snes/d_snes.cpp
"Hyper Street Kart. The Road Warriors (Hack, v1.1)"
"Jurl (HB, v0.5A)"
"Oscar (Euro)"
"Plok! (Euro)"
"Plok! (Euro, French)"
"Plok! (Euro, German)"
"Realm (Euro)"
"Return of Double Dragon - Kencho hacks (Hack)"
"Zombies (Euro)"
"Zombies Ate My Neighbors (Limited Run Games)"
"Zombies Ate My Neighbors. The Sequel (Hack, v1.1)"
"Brutal Zombies Ate My Neighbors (Hack, v3.0)"
"Zool - Ninja of the Nth Dimension (Euro)"
=> d_snes.cpp: added the support to several SNES/Super Famicom games

src/burn/drv/snes/d_snes.cpp
Updated the following games:
msglorydcte to v1.1
tmntfightgme to v2.1
=> adj. in d_snes.cpp

src/burn/drv/snes/d_snes.cpp
"Barkley Shut Up and Jam! (Euro)"
"Hurricanes (Euro)"
"Incantation (Euro)"
"International Superstar Soccer (Euro)"
"International Superstar Soccer Deluxe (Euro)"
"International Tennis Tour (Euro)"
"Jack Nicklaus Golf (Euro)"
"James Bond Jr. (Euro)"
"J.R.R. Tolkien's The Lord of the Rings - Volume One (Euro)"
"Jungle Strike (Euro)"
"King of Dragons, The (Euro)"
"King of the Monsters (Euro)"
"Knights of the Round (Euro)"
"Lamborghini American Challenge (Euro)"
"Last Action Hero (Euro)"
"Lawnmower Man, The (Euro)"
"Lethal Enforcers (Euro)"
"Lethal Weapon (Euro)"
"Magic Boy (Euro)"
"Magic Sword (Euro)"
"World Heroes (Euro)"
"WWF Raw (Euro)"
"WWF Royal Rumble (Euro)"
"WWF Super WrestleMania (Euro)"
"WWF WrestleMania - The Arcade Game (Euro)"
=> d_snes.cpp: added the support to a bunch of games from Europe region
